services:
    _defaults:
        public: true

    engineblock.controller.api.connections:
        class: OpenConext\EngineBlockBundle\Controller\Api\ConnectionsController
        arguments:
            - "@engineblock.metadata.push_metadata_assembler"
            - "@security.authorization_checker"
            - "@engineblock.features"
            - "@engineblock.metadata_push.repository.doctrine"
            - "%engineblock.metadata_push_memory_limit%"

    engineblock.controller.api.consent:
        class: OpenConext\EngineBlockBundle\Controller\Api\ConsentController
        arguments:
            - "@security.authorization_checker"
            - "@engineblock.features"
            - "@engineblock.service.consent"

    engineblock.controller.api.deprovision:
        class: OpenConext\EngineBlockBundle\Controller\Api\DeprovisionController
        arguments:
            - "@security.authorization_checker"
            - "@engineblock.features"
            - "@engineblock.service.deprovision"
            - 'EngineBlock'

    engineblock.controller.api.heartbeat:
        class: OpenConext\EngineBlockBundle\Controller\Api\HeartbeatController

    engineblock.controller.api.metadata:
        class: OpenConext\EngineBlockBundle\Controller\Api\MetadataController
        arguments:
            - "@security.authorization_checker"
            - "@engineblock.features"
            - "@engineblock.service.metadata"

    engineblock.controller.api.attribute_release_policy:
        class: OpenConext\EngineBlockBundle\Controller\Api\AttributeReleasePolicyController
        arguments:
            - "@security.authorization_checker"
            - "@engineblock.service.metadata"
            - "@engineblock.compat.attribute_release_policy_enforcer"
