<?php
return [
    // General
    'button'        =>  'Button: ',
    'required'      =>  'Required',
    'search'        =>  'Search',
    'send_request'  =>  'Send request',
    'back'          =>  'Back',
    'noscript'      =>  'For this page to function optimally you need JavaScript turned on.',
    'language_switcher'     => 'Language switcher',

    // FOOTER
    'log_in_to'     => 'Select an %organisationNoun% to login to %arg1%',
    'helpLink'       => 'https://wiki.surfnet.nl/display/conextsupport/The+WAYF-page',

    // Forms
    'form_general_error'    =>  'Something went wrong when submitting the form.  This might be a faulty internet connection, or some other problem.  Please check your input and try again in a little while.  If the problem persists please contact your administrator.',
    'form_error_name'       =>  'Your name needs to be at least 2 characters long',
    'form_error_email'      =>  'This is an invalid email address',

    // WAYF
    'wayf_nothing_found'        => 'Nothing found',
    'wayf_apu'                  => 'Please try again with some different keywords',
    'wayf_noscript_warning_intro'     => 'Without JavaScript you will not be able to remember previously used accounts.  If you want to use that functionality, please enable JavaScript.',
    'wayf_noscript_warning_end'     => 'You can, off course, still log in.',
    'wayf_delete_account'       => 'Delete from your accounts',
    'wayf_remaining_idps_title' => 'Add an account from the list below',
    'wayf_select_account'       => 'Select an account from the list below',
    'wayf_search_placeholder'   => 'Search...',
    'wayf_search_aria'          => 'Search identity providers',
    'wayf_your_accounts'        => 'Your accounts',
    'wayf_add_account'          => 'Use another account',
    'wayf_no_access'            => 'Sorry, no access for this account',
    'wayf_no_access_account'    => 'No access with this account',
    'wayf_no_access_helpdesk'   => 'If you want, you can request access to this service. We will send the request to the helpdesk of your %orgNoun%.',
    'wayf_noaccess_name'        => 'Your name',
    'wayf_noaccess_email'       => 'Your emailaddress',
    'wayf_noaccess_motivation'  => 'Motivation',
    'wayf_noaccess_success'     => 'Your request for access has been sent.',
    'wayf_defaultIdp_start'     => 'If your %organisation_noun% is not listed,',
    'wayf_defaultIdp_linkText'  => '%defaultIdpName% is available as an alternative.',
    'wayf_idp_title_screenreader' => 'Login with ',

    // Consent
    'consent_h1_text'   => 'Do you give consent to share your information?',
    'consent_h1_text_minimal'   => 'This information will be shared with %arg1%',
    'consent_privacy_header'    => '%target% will receive',
    'consent_attributes_correction_text'    => 'Something incorrect?',
    'consent_ok'    =>  'Yes proceed',
    'consent_identifier_explanation'    => 'The identifier for this service is generated by %suite_name% en differs amongst each service you use through %suite_name%. The service can therefore recognise you as the same user when you return, but services cannot recognise you amongst each other as the same user.',
    'consent_provided_by'   => 'provided by',
    'consent_tooltip_screenreader'  => 'Why do we need this info?',
    'consent_nojs'   => 'Tooltips / modals on this page need JS to work with the keyboard.  If you use a keyboard, please enable JS if you wish to use this functionality.',
    'consent_disclaimer_privacy_statement' => 'needs this information to function properly',
    'consent_disclaimer_privacy_read'    => 'read their',
    'consent_disclaimer_privacy_policy'  => 'privacy policy',
    'consent_disclaimer_secure' => 'is being used by your organisation to securely send your information from your institution to this service (learn more about',
    'consent_reject_text_skeune_header'    => "You don't want to share your data with the service",
    'consent_reject_text_skeune_body'    => "The service you're logging into requires your data to function properly. If you prefer not to share your data, you cannot use this service. By closing your browser or just this tab you prevent your information from being shared with the service. If you change your mind later, please login to the service again and this screen will reappear.",
    'consent_nok_title'     => "You don't want to share your data with the service",
    'consent_nok_text'      => "The service you're logging into requires your data to function properly. If you prefer not to share your data, you cannot use this service. By closing your browser or just this tab you prevent your information from being shared with the service. If you change your mind later, please login to the service again and this screen will reappear.",
    'consent_groupmembership_show_more'     => 'Show more',
    'consent_groupmembership_show_less'     => 'Show less',
];
