services:
    _defaults:
        public: true
        autowire: true

    OpenConext\EngineBlockBundle\Authentication\Repository\DbalConsentRepository:
        public: false

    OpenConext\EngineBlockBundle\Authentication\Repository\UserRepository:
        public: false

    OpenConext\EngineBlockBundle\Authentication\Repository\SamlPersistentIdRepository:
        public: false

    OpenConext\EngineBlockBundle\Authentication\Repository\ServiceProviderUuidRepository:
        public: false

    engineblock.repository.service_provider:
        public: false
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'OpenConext\EngineBlock\Metadata\Entity\ServiceProvider'

    engineblock.repository.identity_provider:
        public: false
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'OpenConext\EngineBlock\Metadata\Entity\IdentityProvider'
