<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>SURFnet Collaboration Infrastructure EngineBlock - Service REST endpoint</title>
    </head>
    <body>
        <h1>Welcome to SURFnet Collaboration Infrastructure EngineBlock - Service API endpoint</h1>
        <p>
            Welcome to the SURFnet COIN Internal endpoint, this endpoint is for SURFnet administrators and services only!<br />
            If you believe you are seeing this in error, please contact <a href="info@surfnet.nl">info@surfnet.nl</a>.<br />
            <br />
        <h2>Supported operations</h2>
        <p>
            <ul>
                <li>
                    <a href="/service/metadata?entityid={$entityid}&gadgeturl={$gadgeturl}&keys={$keys}">
                        /service/metadata?entityid={$entityid}&gadgeturl={$gadgeturl}&keys={$keys}
                    </a>
                    <br />
                    <p>Get the metadata for an entity from the Service Registry.</p>
                    <p>Either directly supply an entity id, or make EngineBlock look up the entity by gadget url</p>
                    <p>Optionally specify only the keys you are interested in, delimited by a comma.</p>
                    <strong>Example:</strong>
                    <a href="/service/metadata?entityid=SURFnetGuests&keys=displayName:en,description:en">
                        https://eb-internal.ebdev.net/service/metadata?entityid=SURFnetGuests&keys=displayName:en,description:en
                    </a>
                    <br />
                    <p>Primarily used to lookup, for a given gadget, to lookup the OAuth data:</p>
                    <ul>
                        <li>coin:oauth:secret</li>
                        <li>coin:oauth:consumer_key</li>
                        <li>coin:oauth:consumer_secret</li>
                        <li>coin:oauth:key_type</li>
                    </ul>
                    <p>Returns JSON data</p>
                </li>
            </ul>
        </p>
    </body>
</html>
