<?php

/**
 * @var EngineBlock_View $this
 */
$title = !empty($_SESSION['feedback_custom']['title'][$this->language()]) ?
            $_SESSION['feedback_custom']['title'][$this->language()] :
            $this->t('error_generic');
$description = !empty($_SESSION['feedback_custom']['description'][$this->language()]) ?
    $this->htmlSpecialCharsText($_SESSION['feedback_custom']['description'][$this->language()]) :
    $this->t('error_generic_desc');

$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title = $layout->title. ' - ' . $title;
$layout->header = $layout->title;
$layout->subheader = $title;
$layout->footerText = $this->t('footer');

?>
<div class="error-wrapper">
    <div class="error-icon"></div>
    <div class="error-text">
        <?= $description;

        require_once realpath(__DIR__ . '/../../../Default/View/Error/include/footer.php');