<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

/**
 * @var EngineBlock_View $this
 */
$title = !empty($_SESSION['feedback_custom']['title'][$this->language()]) ?
            $_SESSION['feedback_custom']['title'][$this->language()] :
            $this->t('error_generic');
$description = !empty($_SESSION['feedback_custom']['description'][$this->language()]) ?
    htmlentities($_SESSION['feedback_custom']['description'][$this->language()], 0, 'UTF-8') :
    $this->t('error_generic_desc');

$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title = $layout->title. ' - ' . $title;
$layout->header = $layout->title;
$layout->subheader = $title;
$layout->footerText = $this->t('footer');

?>
<div class="error-wrapper">
    <div class="error-icon"></div>
    <div class="error-text">
        <?php echo $description;

        require_once realpath(__DIR__ . '/../../../Default/View/Error/include/footer.php');