<!DOCTYPE html>
<html>
    <head>
        <title>SURFnet Collaboration Infrastructure EngineBlock - Error!</title>

        <link rel="stylesheet" href="/css/reset.css">
        <link rel="stylesheet" href="/css/default.css">
        <link rel="stylesheet" href="/css/error.css">
    </head>
    <body>
        <div id="PageContainer">

                    <div id="PortalErrorMessage">
                        <div class="branding-header">
                            <img src="/media/logo-surfnet-small.png" alt="SURFnet" />
                        </div>

                        <h1>Whoops, your session was lost..</h1>

                        <p>
                            Somewhere along the way, your session with us was lost. Please go back and try again.
                            <br /><br />
                        </p>

                        <p>
                            If this does not solve your problem, visit
                            <a href="https://wiki.surfnetlabs.nl/display/conextsupport/">the support page</a>.
                            Here you can find more information about possible causes
                            and how you can contact the support team.
                        </p>

                        <div class="button-row">
                            <a href="#" id="GoBack"  class="submit button-tertiary" onclick="history.back(-2); return false;">
                                Go back
                                <span class="btn-wrap-right">&nbsp;</span>
                            </a>
                        </div>
                    </div>

                        <?php if ($exception) { ?>
        <pre>
            <?php var_dump($exception); ?>
        </pre>

        <?php if ($exception->xdebug_message) { echo $exception->xdebug_message; } ?>
        <? } ?>
        </div>
    </body>
</html>
