<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

?>
<!DOCTYPE html>
<html>
    <head>
        <title>SURFnet Collaboration Infrastructure EngineBlock - Error!</title>

        <link rel="stylesheet" href="/css/reset.css">
        <link rel="stylesheet" href="/css/default.css">
        <link rel="stylesheet" href="/css/error.css">
    </head>
    <body>
        <div id="PageContainer">

                    <div id="PortalErrorMessage">
                        <div class="branding-header">
                            <img src="/media/logo-surfnet-small.png" alt="SURFnet" />
                        </div>

                        <h1>Whoops, message time-out..</h1>

                        <p>
                            We received an out of date message. Please try again.
                            <br /><br />
                        </p>

                        <p>
                            If this does not solve your problem, visit
                            <a href="https://wiki.surfnetlabs.nl/display/conextsupport/">the support page</a>.
                            Here you can find more information about possible causes
                            and how you can contact the support team.
                        </p>

                        <div class="button-row">
                            <a href="#" id="GoBack"  class="submit button-tertiary" onclick="history.back(-2); return false;">
                                Go back
                                <span class="btn-wrap-right">&nbsp;</span>
                            </a>
                        </div>
                    </div>

                        <?php if ($exception) { ?>
        <pre>
            <?php var_dump($exception); ?>
        </pre>

        <?php if ($exception->xdebug_message) { echo $exception->xdebug_message; } ?>
        <? } ?>
        </div>
    </body>
</html>
