<!DOCTYPE html>
<html>
    <head>
        <title>SURFnet Collaboration Infrastructure EngineBlock - Error!</title>

        <link rel="stylesheet" href="/css/reset.css">
        <link rel="stylesheet" href="/css/default.css">
        <link rel="stylesheet" href="/css/error.css">
    </head>
    <body>
        <div id="PageContainer">

                    <div id="PortalErrorMessage">
                        <div class="branding-header">
                            <img src="https://gui.dev.coin.surf.net/coin/media/logo-surfnet-small.png" alt="SURFnet" />
                        </div>

                        <h1>Whoops, unknown issuer..</h1>

                        <p>
                            We received a message from someone we don't know yet..
                            If you are an implementer and want to connect your service with SURFconext,
                            please go to <a href="https://wiki.surfnetlabs.nl/display/conextsupport/">the support page</a>
                            and give us your endpoint data.
                            <br /><br />
                        </p>

                        <p>
                            If this does not solve your problem, visit
                            <a href="https://wiki.surfnetlabs.nl/display/conextsupport/">the support page</a>.
                            Here you can find more information about possible causes
                            and how you can contact the support team.
                        </p>

                        <div class="button-row">
                            <a href="#" id="GoBack"  class="submit button-tertiary" onclick="history.back(-2); return false;">
                                Go back
                                <span class="btn-wrap-right">&nbsp;</span>
                            </a>
                        </div>
                    </div>

                        <?php if ($exception) { ?>
        <pre>
            <?php var_dump($exception); ?>
        </pre>

        <?php if ($exception->xdebug_message) { echo $exception->xdebug_message; } ?>
        <? } ?>
        </div>
    </body>
</html>
