<?php

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title = $layout->title. ' - ' .$this->t('error_unknown_issuer');
$layout->header = $layout->title;
$layout->subheader = $this->t('error_unknown_issuer');
$layout->footerText = $this->t('footer');

?>
<div class="error-wrapper">
    <div class="error-icon"></div>
    <div class="error-text">
        <?= $this->t('error_unknown_issuer_desc');

// Add feedback info from url
$customFeedbackInfo['EntityID'] = $this->_data['entity-id'];
$customFeedbackInfo['Destination'] = $this->_data['destination'];
if (!isset($_SESSION['feedbackInfo'])) {
    $_SESSION['feedbackInfo'] = array();
}
$_SESSION['feedbackInfo'] = array_merge($customFeedbackInfo, $_SESSION['feedbackInfo']);

require_once realpath(__DIR__ . '/../../../Default/View/Error/include/footer.php');
