<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Lidmaatschap van een Virtual Organisation vereist</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow"/>
        <link href="https://espee.surfnet.nl/federate/surfnet/css/screen.css" rel="stylesheet" type="text/css" />
        <link href="https://espee.surfnet.nl/federate/surfnet/css/table.css" rel="stylesheet" type="text/css" />
    </head>
    <body>

        <div class="wrapper">
            <div class="header">
                <a href="http://www.surfnet.nl">
                    <img class="logo" src="https://espee.surfnet.nl/federate/surfnet/img/surfnet_logo.gif" alt="logo" />
                </a>
                <span>SURFnet Service Provider</span>
                <span class="left"></span>
                <span class="right"></span>
                <img src="https://espee.surfnet.nl/federate/surfnet/img/federatie_header.jpg" alt="header img" />
            </div>
            <div class="main">
                <div class="column content">
                    <div class="item">
                    <span class="h2">Lidmaatschap vereist</span> 
                        Je bent succesvol ingelogd bij je Identity Provider, maar om gebruik te kunnen maken van deze dienst moet je ook lid zijn van een Virtuele Organisatie.
                    </div>
                </div>
            </div>
            <div class="footer">
                <p>Bezoek ook:</p>
                <ul>
                    <li><a href="http://www.surfnet.nl">SURFnet</a></li>
                </ul>
                <address>
                    <span><strong>SURFnet bv</strong></span>
                    <span>Radboudkwartier 273</span>
                    <span>Postbus 19035</span>
                    <span>3501 DA Utrecht</span>
                    <span>T +31 302 305 305</span>
                    <span>F +31 302 305 329</span>
                    <a href="mailto:help@surfmedia.nl">
                        help@surfmedia.nl
                    </a>
                    <a class="extra" href="http://www.surfnet.nl/nl/pages/copyright.aspx">
                        Copyright
                    </a>
                    <a class="extra" href="http://www.surfnet.nl/nl/pages/disclaimer.aspx">
                        Disclaimer
                    </a>
                </address>
            </div>
        </div>
    </body>
</html>
