# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    # based on the hardcoded value in
    # https://github.com/OpenConext/OpenConext-engineblock/blob/
    #   4102bffe58a9ecbce3c7c934e0aa8ece46efcf82/library/EngineBlock/Application/Bootstrapper.php#L242
    locale: en
    container.autowiring.strict_mode: true

    # This value is used as cache-buster, replaced by the release script
    asset_version: "#ASSET_VERSION#"
