<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>SURFnet Collaboration Infrastructure EngineBlock - Default Homepage</title>
    </head>
    <body>
        <h1>Welcome to SURFnet Collaboration Infrastructure EngineBlock - Default Homepage!</h1>
        <p>
            If you see this message you've probably configured EngineBlock to not use any specialised routing. <br />
            To run an action go to: /modulename/controllername/actionname.
        </p>
    </body>
</html>
