<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->setLayout('1-column-blue-grey');

$layout->subheader = 'Welcome to SURFnet Collaboration Infrastructure EngineBlock - Internal endpoint';
?>
        <p>
            Welcome to the SURFnet COIN Internal endpoint, this endpoint is for SURFnet administrators and services only!<br />
            If you believe you are seeing this in error, please contact <a href="info@surfnet.nl">info@surfnet.nl</a>.<br />
            <br />
            See also: <a href="/service">/service</a>.<br />
            See also: <a href="/social">/social</a>.<br />
            See also: <a href="/cron">/cron</a>.
        </p>
    </body>
</html>
