<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>SURFnet Collaboration Infrastructure EngineBlock - Internal endpoint</title>
    </head>
    <body>
        <h1>Welcome to SURFnet Collaboration Infrastructure EngineBlock - Internal endpoint</h1>
        <p>
            Welcome to the SURFnet COIN Internal endpoint, this endpoint is for SURFnet administrators and services only!<br />
            If you believe you are seeing this in error, please contact <a href="info@surfnet.nl">info@surfnet.nl</a>.<br />
            <br />
            See also: <a href="/service">/service</a>.<br />
            See also: <a href="/social">/social</a>.
        </p>
    </body>
</html>
