<?php

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title = $layout->title. ' - Error';
$layout->header = $layout->title;
$layout->subheader = $this->t('error_unknown_service_provider', $this->_data['entity-id']);
$layout->footerText = $this->t('footer');
?>
<div class="error-wrapper">
    <div class="error-icon"></div>
    <div class="error-text">
        <?= $this->t('error_unknown_service_provider_desc');

// Add feedback info from url
$customFeedbackInfo['EntityID'] = $this->_data['entity-id'];
if (!isset($_SESSION['feedbackInfo'])) {
    $_SESSION['feedbackInfo'] = array();
}
$_SESSION['feedbackInfo'] = array_merge($customFeedbackInfo, $_SESSION['feedbackInfo']);

require_once realpath(__DIR__ . '/../../../Default/View/Error/include/footer.php');
