monolog:
    channels: ["%logger.channel%", "authentication"]
    handlers:
        main:
            type: fingers_crossed
            activation_strategy: engineblock.logger.manual_or_error_activation_strategy
            passthru_level: "%logger.fingers_crossed.passthru_level%"
            handler: nested
            channels: [!authentication]
        nested:
            type:      stream
            path:      php://stderr
            formatter: engineblock.logger.formatter.syslog_json
        authentication:
            type:      stream
            path:      php://stderr
            level:     INFO
            channels:  [authentication]
            formatter: engineblock.logger.formatter.syslog_json
        console:
            type: console
            process_psr_3_messages: false
            channels: [!event, !doctrine, !console]
