<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>SURFnet Collaboration Infrastructure EngineBlock - OpenSocial API</title>
    </head>
    <body>
        <h1>Welcome to SURFnet Collaboration Infrastructure EngineBlock OpenSocial API!</h1>
        <h2>OpenSocial URLs</h2>
        <ul>
            <li>
                <a href="/social/people/{$uid}">
                    /social/people/{$uid}
                </a>
                <br />
                <p>Get the person information in JSON format.</p>
                <strong>Example:</strong>
                <a href="/social/people/urn:collab:person:surfnet.nl:hansz">
                    /social/people/urn:collab:person:surfnet.nl:hansz
                </a>
                <br />
                <p>Use ?fields=x,y,z to only get fields x,y and z.</p>

                <p>Valid fields are:</p>
                <ul>
                    <li>id</li>
                    <li>name</li>
                    <li>displayname</li>
                    <li>nickname</li>
                    <li>email</li>
                </ul>
            </li>
        </ul>
    </body>
</html>
