services:

    # Aliased the monolog logger for OpenConextEngineBlockBundle who boots the ApplicationSingleton without use of DI.
    # Remove this once ApplicationSingleton is removed, or uses DI.
    monolog.logger.public:
      alias: 'monolog.logger'
      public: true

    engineblock.logger.additional_info_formatter:
        class: OpenConext\EngineBlock\Logger\Formatter\AdditionalInfoFormatter
        arguments:
            - "@engineblock.logger.line_formatter"

    engineblock.logger.line_formatter:
        public: false
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "%logger.line_format%"

    engineblock.logger.manual_or_error_activation_strategy:
        class: OpenConext\EngineBlock\Logger\Handler\FingersCrossed\ManualOrDecoratedActivationStrategy
        factory: [OpenConext\EngineBlock\Logger\Handler\FingersCrossed\ManualOrErrorLevelActivationStrategyFactory, createActivationStrategy]
        arguments:
            - { action_level: "%logger.fingers_crossed.action_level%" }
        public: true

    engineblock.logger.processor.request_id_processor:
        class: OpenConext\EngineBlock\Logger\Processor\RequestIdProcessor
        arguments:
            - "@engineblock.request.request_id"
        tags:
            - { name: monolog.processor, method: processRecord }

    engineblock.logger.processor.session_id_processor:
        class: OpenConext\EngineBlock\Logger\Processor\SessionIdProcessor
        tags:
            - { name: monolog.processor, method: processRecord }

    engineblock.logger.formatter.syslog_json:
        class: OpenConext\EngineBlockBundle\Monolog\Formatter\SyslogJsonFormatter

    engineblock.logger.authentication:
        class: OpenConext\EngineBlock\Logger\AuthenticationLogger
        arguments:
            - "@monolog.logger.authentication"
