parameters:
    # This value is used as cache-buster
    asset_version: "dev"
    global.site_notice.show: false

framework:
    translator:
        enabled: true
        fallbacks: [ "%locale%" ]
        paths:
            - '%kernel.project_dir%/languages'
            - '%kernel.project_dir%/theme/base/translations'
            - '%kernel.project_dir%/theme/%theme.name%/translations'
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

twig:
    cache: false
    auto_reload: true
    debug: true
    strict_variables: false
