parameters:
    api.users.nameIdLookup.username: nameid
    api.users.nameIdLookup.password: secret
    feature_api_users_nameid_lookup: true
    encryption_keys:
        default:
            publicFile: /config/engine/engineblock.crt
            privateFile: /config/engine/engineblock.pem
        rollover:
            publicFile: '%kernel.project_dir%/src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/keys/rolled-over.crt'
            privateFile: '%kernel.project_dir%/src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/keys/rolled-over.key'
