<?php
/** @var Zend_Layout $layout */
$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title = $layout->title. ' - API';
$layout->header = $layout->title;
$layout->footerText = $this->t('footer');
?>
<div>
    <h2>Welcome to the EngineBlock API index page!</h2>
    <p>
        We currently only support 1 action, pushing metadata configuration.
        To do this POST a valid JSON document with 'connections' to /connections,
        using the engineApi.user and engineApi.password in HTTP Basic authentication.
    </p>
</div>
