<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

// The current language
$lang = $this->language();

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();

// Set Layout variables
$layout->header = $this->t('deleteuser_success_header');
$layout->title = $layout->title. ' - ' .$layout->header;
$layout->subheader = $this->t('deleteuser_success_subheader');
$layout->footerText = $this->t('footer');

$layout->getView()->inlineScript()->appendFile('/javascript/screen.js');

?>
<div>
    <p>
        <?php echo $this->t('deleteuser_success_desc'); ?>
    </p>
</div>