<?php
/** @var Zend_Layout $layout */
$layout = $this->layout();

// Set Layout variables
$layout->header = $this->t('deleteuser_success_header');
$layout->title = $layout->title. ' - ' .$layout->header;
$layout->subheader = $this->t('deleteuser_success_subheader');
$layout->footerText = $this->t('footer');

$layout->getView()->inlineScript()->appendFile('/javascript/screen.js');

?>
<div class="mod-content">
    <h1><?php echo $this->t('deleteuser_success_subheader');?></h1>
    <p><?= $this->t('deleteuser_success_desc'); ?></p>
</div>