_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix: /_error

_functional_testing:
    prefix:   functional-testing
    resource: "../functional_testing/functional_testing.yml"
