doctrine:
    dbal:
        default_connection: engineblock_test
        connections:
            engineblock:
                driver:   "%database.test.driver%"
                server_version: "%database.test.server_version%"
                dbname:   "%database.dbname%"
                host:     "%database.test.host%"
                port: "%database.port%"
                user: "%database.user%"
                password: "%database.password%"
            engineblock_test:
                driver:   "%database.test.driver%"
                server_version: "%database.test.server_version%"
                dbname:   "%database.test.dbname%"
                host:     "%database.test.host%"
                port:     "%database.test.port%"
                user:     "%database.test.user%"
                password: "%database.test.password%"
