doctrine:
    dbal:
        default_connection: engineblock_test
        connections:
            engineblock:
                driver:   pdo_mysql         # This must be PDO until all database interaction runs through doctrine
                server_version: '10.6.0-MariaDB'
                dbname:   "%database.dbname%"
                host:     "%database.test.host%"
                port:     "%database.port%"
                user:     "%database.user%"
                password: "%database.password%"
            engineblock_test:
                driver:   pdo_mysql         # This must be PDO until all database interaction runs through doctrine
                server_version: '10.6.0-MariaDB'
                dbname:   "%database.test.dbname%"
                host:     "%database.test.host%"
                port:     "%database.test.port%"
                user:     "%database.test.user%"
                password: "%database.test.password%"
