---

version: "3.8"

services:
    openconext:
        image: ghcr.io/openconext/openconext-basecontainers/php85-apache2-node24:latest
        volumes:
            - ../:/home/runner/work/OpenConext-engineblock
        working_dir: /home/runner/work/OpenConext-engineblock
