<ul id="faq" class="faq">
                    <li class="open">
                        <h3>Why this screen?</h3>
                        <p>You can log in to this service with your institutional account. In this screen, you fill in the institution where you want to log in.</p>
                        <span class="openClose">Close</span> </li>
                    <li>
                        <h3>What is SURFfederatie?</h3>
                        <p>SURFfederatie allows you to access the online services provided by a large number of external providers ñ such as webshops, video services, and scientific/scholarly articles ñ with the user name and password issued to you by your institution. SURFfederatie is a secure central ìintermediaryî between your institution and the providers of the online services.</p>
                        <span class="openClose">Close</span> </li>
                    <li>
                        <h3>How do you log in via SURFfederatie?</h3>
                        <ul>
	                        <li>Click on your institution in this screen.</li>
							<li>You will then be taken to the log-in page for your institution, where you can log in.</li>
							<li>Your institution will notify SURFfederatie that you have logged in successfully.</li>
							<li>You will be taken to the service for which you have logged in. You can then make use of that service.</li>
                        </ul>

                        <span class="openClose">Close</span> </li>
                    <li>
                        <h3>Is SURFfederatie secure?</h3>
                        <p>Your institution and SURFfederatie both believe that user privacy is extremely important.<br />
<br />
Personal details are only provided to a service provider if that is necessary so as to use the service. Contractual agreements between your institution, SURFfederatie, and the service provider guarantee that your personal details will be dealt with carefully.<br />
<br />
If you have any questions about how your personal details will be dealt with within SURFfederatie, you can contact your institution or the service provider where you are trying to log in.
</p>
                        <span class="openClose">Close</span> </li>
                    <li>
                        <h3>My institution is not on the list. What should I do?</h3>
                        <p>If your institution is not listed, then it is probably not yet connected to SURFfederatie. Go back to the page for the service. In some cases, there will be alternative ways of logging in.</p>
                        <span class="openClose">Close</span> </li>
                    <li>
                        <h3>My institution does not provide access to the service. What should I do?</h3>
                        <p>It is possible that your institution is connected to SURFfederatie but has not (or not yet) made any arrangements with the service provider about the use of the service. That means that you do not have access to the service. Click on your institution. You can then submit a request to the institution for access to the service. Your request may lead to your institution making the necessary arrangements with the service provider.</p>
                        <span class="openClose">Close</span> </li>
                    <li>
                        <h3>I have asked my institution for access but I still can't get access. Why not?</h3>
                        <p>SURFnet has forwarded your request to the right person at your institution, who will take the necessary action. SURFnet has no control over how fast you will receive an answer or be given access.</p>
                        <span class="openClose">Close</span> </li>
                    <li>
                        <h3>I cannot select my institution. What should I do?</h3>
                        <p>The SURFfederatie options screen can be used in the most popular browsers, including Internet Explorer 7 and 8, Firefox, Chrome, and Safari. Other browsers may not be supported. Your browser must also support the use of cookies and JavaScript.</p>
                        <span class="openClose">Close</span> </li>
</ul>