<ul id="faq" class="faq">
    <li class="open">
        <h3><?php echo $this->t('question_screen'); ?></h3>
        <?php echo $this->t('answer_screen'); ?>
        <span class="openClose"><?php echo $this->t('close_question'); ?></span>
    </li>
    <li class="open">
        <h3><?php echo $this->t('question_surfconext'); ?></h3>
        <?php echo $this->t('answer_surfconext'); ?>
        <span class="openClose"><?php echo $this->t('close_question'); ?></span>
    </li>
    <li class="open">
        <h3><?php echo $this->t('question_log_in'); ?></h3>
        <?php echo $this->t('answer_log_in'); ?>
        <span class="openClose"><?php echo $this->t('close_question'); ?></span>
    </li>
    <li class="open">
        <h3><?php echo $this->t('question_security'); ?></h3>
        <?php echo $this->t('answer_security'); ?>
        <span class="openClose"><?php echo $this->t('close_question'); ?></span>
    </li>
    <li class="open">
        <h3><?php echo $this->t('question_institution_not_listed'); ?></h3>
        <?php echo $this->t('answer_institution_not_listed'); ?>
        <span class="openClose"><?php echo $this->t('close_question'); ?></span>
    </li>
    <li class="open">
        <h3><?php echo $this->t('question_institution_no_access'); ?></h3>
        <?php echo $this->t('answer_institution_no_access'); ?>
        <span class="openClose"><?php echo $this->t('close_question'); ?></span>
    </li>
    <li class="open">
        <h3><?php echo $this->t('question_asked_institution_access'); ?></h3>
        <?php echo $this->t('answer_asked_institution_access'); ?>
        <span class="openClose"><?php echo $this->t('close_question'); ?></span>
    </li>
    <li class="open">
        <h3><?php echo $this->t('question_cannot_select'); ?></h3>
        <?php echo $this->t('answer_cannot_select'); ?>
        <span class="openClose"><?php echo $this->t('close_question'); ?></span>
    </li>
</ul>