<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

/** @var Zend_Layout $layout */
$layout = $this->layout();
$layout->setLayout('empty');
?>
<p class="back"><a id="back_link" href="#"><?php echo $this->t('back'); ?></a>
</p>
<h2><?php echo $this->t('help_header'); ?></h2>
<p><?php echo $this->t('help_description'); ?></p>
<div class="results">
    <div id="scrollViewportHelp">
        <ul id="faq" class="faq">
            <li class="open">
                <h3><?php echo $this->t('question_consentscreen'); ?></h3>
                <?php echo $this->t('answer_consentscreen'); ?>
                <span class="openClose"><?php echo $this->t('close_question'); ?></span>
            </li>
            <li>
                <h3><?php echo $this->t('question_consentinfo'); ?></h3>
                <?php echo $this->t('answer_consentinfo'); ?>
                <span class="openClose"><?php echo $this->t('close_question'); ?></span>
            </li>
            <li>
                <h3><?php echo $this->t('question_consentno'); ?></h3>
                <?php echo $this->t('answer_consentno'); ?>
                <span class="openClose"><?php echo $this->t('close_question'); ?></span>
            </li>
            <li>
                <h3><?php echo $this->t('question_consentagain'); ?></h3>
                <?php echo $this->t('answer_consentagain'); ?>
                <span class="openClose"><?php echo $this->t('close_question'); ?></span>
            </li>
            <li>
                <h3><?php echo $this->t('question_surfconext'); ?></h3>
                <?php echo $this->t('answer_surfconext'); ?>
                <span class="openClose"><?php echo $this->t('close_question'); ?></span>
            </li>
            <li>
                <h3><?php echo $this->t('question_log_in'); ?></h3>
                <?php echo $this->t('answer_log_in'); ?>
                <span class="openClose"><?php echo $this->t('close_question'); ?></span>
            </li>
            <li>
                <h3><?php echo $this->t('question_security'); ?></h3>
                <?php echo $this->t('answer_security'); ?>
                <span class="openClose"><?php echo $this->t('close_question'); ?></span>
            </li>
        </ul>
    </div>
</div>
