<?php
/** @var Zend_Layout $layout */
$layout = $this->layout();
$layout->setLayout('empty');
?>
<div class="mod-form">
  <?= $this->t('request_access_instructions') ?>

  <form id="request_access_form" action="#" method="post" class="apply clearfix">
    <input name="spName" type="hidden" value="<?= $queryParameters['spName']; ?>">
    <input name="spEntityId" type="hidden" value="<?=  $queryParameters['spEntityId']; ?>">

    <?php if (isset($nameError) || isset($emailError) || isset($institutionError) || isset($commentError)): ?>
      <div class="errors">
        <ul>
        <?php if (isset($nameError)) : ?>
            <li><?= $this->t('name_error'); ?></li>
        <?php endif; ?>

        <?php if (isset($emailError)) : ?>
          <li><?= $this->t('email_error'); ?></li>
        <?php endif; ?>

        <?php if (isset($institutionError)) : ?>
          <li><?= $this->t('institution_error'); ?></li>
        <?php endif; ?>

        <?php if (isset($commentError)) : ?>
          <li><?= $this->t('comment_error'); ?></li>
        <?php endif; ?>
        </ul>
      </div>
    <?php endif; ?>

    <fieldset>
      <div class="input">
        <label for="name"><?= $this->t('name'); ?>:</label>
        <input name="name" type="text" id="name" value="<?= $queryParameters['name']; ?>">
      </div>

      <div class="input">
        <label for="email"><?= $this->t('email'); ?>:</label>
        <input name="email" type="email" id="email" value="<?= $queryParameters['email']; ?>" />
      </div>

      <div class="input">
        <label for="institution"><?= $this->t('institution'); ?>:</label>
        <input name="institution" type="text" id="institution" value="<?= $queryParameters['institution']; ?>" />
      </div>

      <div class="input">
        <label for="comment" class="top"><?= $this->t('comment'); ?>:</label>
        <textarea name="comment" id="comment"><?= $queryParameters['comment']; ?></textarea>
      </div>
    </fieldset>

    <fieldset>
      <div class="actions">
        <button id="request_access_submit" class="c-button"><?= $this->t('send'); ?></button>
        <button id="cancel_request_access" class="cancel c-button outline close-modal"><?= $this->t('cancel'); ?></button>
      <div>
    </fieldset>
  </form>
</div>
