<?php
$hostUrl = 'https://' . $_SERVER['HTTP_HOST'];
return array(
    $hostUrl .'/authentication/sp/metadata' =>
    array(
        'AssertionConsumerService:0:Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
        'AssertionConsumerService:0:Location' => $hostUrl .'/authentication/sp/consume-assertion',
        'contacts:0:contactType' => 'technical',
        'contacts:0:emailAddress' => 'support@openconext.org',
        'contacts:0:givenName' => 'Support',
        'contacts:0:surName' => 'OpenConext',
        'contacts:1:contactType' => 'support',
        'contacts:1:emailAddress' => 'support@openconext.org',
        'contacts:1:givenName' => 'Support',
        'contacts:1:surName' => 'OpenConext',
        'contacts:2:contactType' => 'administrative',
        'contacts:2:emailAddress' => 'support@openconext.org',
        'contacts:2:givenName' => 'Support',
        'contacts:2:surName' => 'OpenConext',
        'description:en' => 'OpenConext SSO Proxy',
        'description:nl' => 'OpenConext SSO Proxy',
        'logo:0:height' => 96,
        'logo:0:url' => 'https://static.demo.openconext.org/media/conext_logo.png',
        'logo:0:width' => 96,
        'name:en' => 'OpenConext Engine',
        'name:nl' => 'OpenConext Engine',
        'NameIDFormats:0' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
        'NameIDFormats:1' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
        'NameIDFormats:2' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified',
        'redirect.sign' => false,
        'SingleLogoutService' => 'https://engine.surfconext.nl/logout#sp',
        'SingleLogoutService_Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        'SingleLogoutService_Location' => 'https://engine.surfconext.nl/logout#sp',
        'url:en' => '',
        'url:nl' => '',
        'workflowState' => 'prodaccepted'
    ),
    $hostUrl .'/dummy/sp' =>
    array(
        'AssertionConsumerService:0:Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
        'AssertionConsumerService:0:Location' => $hostUrl .'/dummy/sp',
        'contacts:0:contactType' => 'technical',
        'contacts:0:emailAddress' => 'support@openconext.org',
        'contacts:0:givenName' => 'Support',
        'contacts:0:surName' => 'OpenConext',
        'contacts:1:contactType' => 'support',
        'contacts:1:emailAddress' => 'support@openconext.org',
        'contacts:1:givenName' => 'Support',
        'contacts:1:surName' => 'OpenConext',
        'contacts:2:contactType' => 'administrative',
        'contacts:2:emailAddress' => 'support@openconext.org',
        'contacts:2:givenName' => 'Support',
        'contacts:2:surName' => 'OpenConext',
        'description:en' => 'OpenConext SSO Proxy',
        'description:nl' => 'OpenConext SSO Proxy',
        'logo:0:height' => 96,
        'logo:0:url' => 'https://static.demo.openconext.org/media/conext_logo.png',
        'logo:0:width' => 96,
        'name:en' => 'OpenConext Engine',
        'name:nl' => 'OpenConext Engine',
        'NameIDFormats:0' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
        'NameIDFormats:1' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
        'NameIDFormats:2' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified',
        'redirect.sign' => false,
        'SingleLogoutService' => 'https://engine.surfconext.nl/logout#sp',
        'SingleLogoutService_Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        'SingleLogoutService_Location' => 'https://engine.surfconext.nl/logout#sp',
        'url:en' => '',
        'url:nl' => '',
        'workflowState' => 'prodaccepted',
        'coin:no_consent_required' => true
    ),
    $hostUrl .'/dummy/sp?nr=2' =>
    array(
        'AssertionConsumerService:0:Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
        'AssertionConsumerService:0:Location' => $hostUrl .'/dummy/sp#2',
        'contacts:0:contactType' => 'technical',
        'contacts:0:emailAddress' => 'support@openconext.org',
        'contacts:0:givenName' => 'Support',
        'contacts:0:surName' => 'OpenConext',
        'contacts:1:contactType' => 'support',
        'contacts:1:emailAddress' => 'support@openconext.org',
        'contacts:1:givenName' => 'Support',
        'contacts:1:surName' => 'OpenConext',
        'contacts:2:contactType' => 'administrative',
        'contacts:2:emailAddress' => 'support@openconext.org',
        'contacts:2:givenName' => 'Support',
        'contacts:2:surName' => 'OpenConext',
        'description:en' => 'OpenConext SSO Proxy',
        'description:nl' => 'OpenConext SSO Proxy',
        'logo:0:height' => 96,
        'logo:0:url' => 'https://static.demo.openconext.org/media/conext_logo.png',
        'logo:0:width' => 96,
        'name:en' => 'OpenConext Engine',
        'name:nl' => 'OpenConext Engine',
        'NameIDFormats:0' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
        'NameIDFormats:1' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
        'NameIDFormats:2' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified',
        'redirect.sign' => false,
        'SingleLogoutService' => 'https://engine.surfconext.nl/logout#sp',
        'SingleLogoutService_Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        'SingleLogoutService_Location' => 'https://engine.surfconext.nl/logout#sp',
        'url:en' => '',
        'url:nl' => '',
        'workflowState' => 'prodaccepted',
        'coin:no_consent_required' => true
    )
);
