---
  - name: Update LDAP
    command: ldapmodify -x -D {{ldap_admin_bind_dn}} -h localhost -w {{ldap_admin_password}} -f {{item}}
    with_items:
      - "{{ engine_release_dir }}/ldap/changes/addDeprovisionWarningSentAttributes.ldif"
      - "{{ engine_release_dir }}/ldap/changes/addCollabPersonUUID.ldif"
    ignore_errors: true

  - name: Run EngineBlock migrations
    command: ./bin/migrate
    args:
      chdir: "{{ engine_release_dir }}"

  - name: Activate new EngineBlock
    file: src={{ engine_release_dir }} dest={{ engine_current_release_symlink }} state=link