services:
    api.security.http_basic_entry_point:
        class: OpenConext\EngineBlock\ApiBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - "engine-api.%domain%"

    api.service.features:
        class: OpenConext\EngineBlock\ApiBundle\Service\FeaturesService
        arguments:
            - %api.features.metadata_push.enabled%
            - %api.features.consent_listing.enabled%
