<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

/**
 * See OpenConext-engineblock/library/EngineBlock/Corto/Module/Service/ProvideConsent.php#84
 */
if (!isset($action)) {
    throw new EngineBlock_View_Exception('No Consent action given to consent screen');
}
if (!isset($ID)) {
    throw new EngineBlock_View_Exception('No ID given to consent screen');
}
if (!isset($attributes)) {
    throw new EngineBlock_View_Exception('No Attributes given to consent screen');
}
if (!isset($commonName)) {
    throw new EngineBlock_View_Exception('No common name given to consent screen');
}
if (!isset($sp)) {
    throw new EngineBlock_View_Exception('No SP information given to consent screen');
}
if (!isset($idp)) {
    throw new EngineBlock_View_Exception('No IdP information given to consent screen');
}

// The current language
$lang = isset($_POST['lang']) && in_array($_POST['lang'], array('nl','en')) ? $_POST['lang'] : $this->language();
$fallback_lang = ($lang == 'en' ? 'nl' : 'en');

$spName         = isset($sp['Name'][$lang])  ? $sp['Name'][$lang] : $sp['Name'][$fallback_lang];
$idpName        = isset($idp['Name'][$lang]) ? $idp['Name'][$lang] : $idp['Name'][$fallback_lang];

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();

// Set different layout
$layout->setLayout('consent');

// Set Layout variables
$layout->use_header = false;
$layout->title      = $layout->title . ' - '. $this->t('consent_header', htmlentities($spName));
$layout->subheader  = $this->t('consent_subheader', $spName);
$layout->footerText = $this->t('footer');

// Set profile page Url
$profileUrl = EngineBlock_View::profileUrl();

/** @var $view Zend_View */
$view = $layout->getView();
/** @var $inlineScriptHelper Zend_View_Helper_InlineScript */
$inlineScriptHelper = $view->getHelper('InlineScript');
$inlineScriptHelper->appendScript('$("#accept_terms_button").focus();');
$inlineScriptHelper->appendScript('
(function() {
    var d = new Discover();
    d.linkHelp();
' . (isset($_POST['show-help']) && $_POST['show-help'] === 'yes' ? 'd.showHelp(0)' : '') .
' })();');
?>
<style>
    table {
        width: 100%;
    }
</style>
<h2><?php echo $this->t('consent_header_info'); ?></h2>

<p>
    <?php echo $this->t('consent_sp_idp_info', $spName, $idpName); ?>
</p>

<div>
    <?php $this->sortConsentDisplayOrder($attributes) ?>
    <table>
    <?php foreach ($attributes as $uid => $attributeValues) { ?>
        <?php $attributeName = $this->getDisplayName($uid, $lang, false)?>
        <?php if ($attributeName) : ?>
            <tr>
                <td>
                    <?= $attributeName ?>
                </td>
                <td>
                    <?php /** Single attribute value */ if (count($attributeValues)==1) { ?>
                        <?php echo htmlspecialchars($attributeValues[0]);?>
                    <?php } /** Multiple attribute values */ else { ?>
                        <ul>
                            <?php foreach ($attributeValues as $value) { ?>
                                <li><?php echo htmlspecialchars($value); ?></li>
                            <?php } ?>
                        </ul>
                    <?php } ?>
                </td>
            </tr>
        <?php endif; ?>
    <?php } ?>
    <?php if ($nameId) : ?>
        <tr>
            <td>
                <?php echo $this->t('name_id'); ?>
            </td>
            <td>
                <?= $nameId ?>
            </td>
        </tr>
    <?php endif; ?>
    </table>
</div>

<style>
    input.submit {
        height: 3em;
    }
</style>

<div id="approve">
<!-- YES -->
<form id="accept" method="post" action="<?php echo htmlspecialchars($action); ?>">
        <input type="hidden" name="ID"      value="<?php echo htmlspecialchars($ID); ?>">
        <input type="hidden" name="consent" value="yes" />

        <input id="accept_terms_button"
               class="submit bigbutton"
               type="submit"
               value="<?php echo $this->t('consent_accept'); ?>"
               />
</form>

<!-- NO -->
<form id="reject" method="post" action="<?php echo htmlspecialchars($action); ?>">
        <input type="hidden" name="ID"      value="<?php echo htmlspecialchars($ID); ?>">
        <input type="hidden" name="consent" value="no" />

        <a id="decline_terms_button" style="line-height: 40px;" href="javascript:;" onclick="document.getElementById('reject').submit();">
            <?php echo $this->t('consent_decline'); ?>
        </a>
</form>
</div>

<p class="grey"><?php echo $this->t('consent_notice'); ?></p>

<?php if (isset($sp['Eula'])) : ?>
    <?php echo $this->t('sp_terms_of_service', $spName, $sp['Eula']); ?>
<?php endif; ?>

