<?php
/**
 * Injected:
 *
 * @var array $response
 * @var array $idp
 * @var array $attributes
 * @var EngineBlock_Corto_ProxyServer $this
 */

$validator = new EngineBlock_Attributes_Validator($attributes);
$attributesValidated = $validator->validate();
?>
IdP
===
<?php
echo 'Name               ' . $idp['Name']['en'] . PHP_EOL;
echo 'Entity ID          ' . $idp['EntityID'] . PHP_EOL;
echo 'Workflow Status:   ' . $idp['WorkflowState'] . PHP_EOL;
?>


SAML2 Subject
=============
<?php
echo 'NameID             ' . $response['saml:Assertion']['saml:Subject']['saml:NameID']['__v'] ?>



Attributes
==========
<?php foreach ($validator->getErrorsForMissingAttributes() as $error): ?>
Error: <?php echo call_user_func_array('sprintf', $error); ?>
<?php endforeach; ?>
<?php foreach ($validator->getWarningsForMissingAttributes() as $warning): ?>
Warning: <?php echo call_user_func_array('sprintf', $warning); ?>
<?php endforeach; ?>


<?php foreach ($attributes as $attributeName => $attributeValues): ?>
"<?php echo $attributeName ?>"
----------------------------------------------------------
Name: <?php echo $this->getAttributeName($attributeName, 'en', false) ?>

Values:
<?php   foreach ($attributeValues as $attributeValue): ?>
* "<?php echo $attributeValue ?>"
<?php   endforeach; ?>
<?php   foreach ($validator->getErrors($attributeName) as $error): ?>
Error: <?php echo call_user_func_array('sprintf', $error); ?>
<?php   endforeach; ?>
<?php   foreach ($validator->getWarnings($attributeName) as $warning): ?>
Warning: <?php echo call_user_func_array('sprintf', $warning); ?>
<?php   endforeach; ?>


<?php endforeach; ?>


Raw data
========

Entity.php
----------------------------------------------------------
<?php var_export($idp) ?>


Response.php
----------------------------------------------------------
<?php var_export($response) ?>