<?php

/**
 * Injected:
 * @var EngineBlock_Saml2_ResponseAnnotationDecorator $response
 * @var array $idp
 * @var array $attributes
 * @var EngineBlock_View $this
 *
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title      = $layout->title . ' - ' . $this->t('idp_debugging_title');
$layout->header     = $layout->title;
$layout->subheader  = $this->t('idp_debugging_title');
$layout->footerText = $this->t('footer');

$validator = new EngineBlock_Attributes_Validator($attributes);
$attributesValidated = $validator->validate();
?>

<?php if ($attributesValidated) : ?>
<img src="/media/famfamfam_silk_icons_v013/icons/tick.png" alt="" />
<?= $this->t('attributes_validation_succeeded'); ?>
<?php else: ?>
    <?php if (count($validator->getErrors()) > 0): ?>
<img src="/media/famfamfam_silk_icons_v013/icons/exclamation.png" alt="" style="vertical-align: bottom" />
    <?php else: ?>
<img src="/media/famfamfam_silk_icons_v013/icons/error.png" alt="" style="vertical-align: bottom" />
    <?php endif; ?>

<?= $this->t('attributes_validation_failed'); ?>
<?php endif; ?>

<form method="post" style="float: right">
    <input type="hidden" name="clear" value="true" />
    <input type="submit" value="Retry" />
</form>
<hr style="clear: both" />

<h2>Identity Provider</h2>
<table>
    <tr>
        <th>
            Logo
        </th>
        <td>
            <img src="<?= $idp['Logo']['URL'] ?>" />
        </td>
    </tr>
    <tr>
        <th>
            <?= $this->t('name'); ?>
        </th>
        <td>
            <?= $this->htmlSpecialCharsText($idp['Name']['en'], ENT_COMPAT, 'UTF-8') ?>
        </td>
    </tr>
    <tr>
        <th>
            Entity ID
        </th>
        <td>
            <?= $this->htmlSpecialCharsText($idp['EntityID']) ?>
        </td>
    </tr>
    <tr>
        <th>
            Workflow Status
        </th>
        <td <?php if ($idp['WorkflowState']==='production') { echo 'style="color: green"';} ?>>
            <?= $this->htmlSpecialCharsText($idp['WorkflowState']) ?>
        </td>
    </tr>
</table>
<hr />
<h2>SAML2 Subject</h2>
<table>
    <tr>
        <th>NameID</th>

        <td>
            <?php $nameId = $response->getAssertion()->getNameId(); echo $this->htmlSpecialCharsText($nameId['Value']); ?>
        </td>
    </tr>
</table>
<hr />
<h2><?= $this->t('attributes') ?></h2>
<?php foreach ($validator->getErrorsForMissingAttributes() as $error): ?>
    <p class="error">
        <img src="/media/famfamfam_silk_icons_v013/icons/exclamation.png" alt="[error]" style="vertical-align: bottom" /> <?php
    echo $this->htmlSpecialCharsText(call_user_func_array(array($this, 'translate'), $error));
    ?></p>
<?php endforeach; ?>
<?php foreach ($validator->getWarningsForMissingAttributes() as $warning): ?>
    <p class="warning">
        <img src="/media/famfamfam_silk_icons_v013/icons/error.png" alt="[error]" style="vertical-align: bottom" /> <?php
    echo $this->htmlSpecialCharsText(call_user_func_array(array($this, 'translate'), $warning));
    ?></p>
<?php endforeach; ?>
<table>
    <thead>
        <tr>
            <th>
                SURFconext Display Name
            </th>
            <th>
                <?= $this->t('name'); ?>
            </th>
            <th>
                <?= $this->t('value'); ?>
            </th>
            <th>
                <?= $this->t('validation'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($attributes as $attributeName => $attributeValues) { ?>
        <tr>
            <td>
                <?= $this->getAttributeName($attributeName, 'en', false) ?>
            </td>
            <td>
                <?= $this->htmlSpecialCharsText($attributeName); ?>
            </td>
            <td>
                <?php /** Single attribute value */ if (count($attributeValues)==1) { ?>
                <?= $this->htmlSpecialCharsText($attributeValues[0]);?>
                <?php } /** Multiple attribute values */ else { ?>
                <ul>
                    <?php foreach ($attributeValues as $value) { ?>
                    <li><?= $this->htmlSpecialCharsText($value); ?></li>
                    <?php } ?>
                </ul>
                <?php } ?>
            </td>
            <td>
                <?php if ($validator->isValid($attributeName)): ?>
                <img src="/media/famfamfam_silk_icons_v013/icons/tick.png" alt="valid" />
                <?php else:
                    foreach ($validator->getErrors($attributeName) as $error) {
                        echo '<p class="error">' .
                                '<img src="/media/famfamfam_silk_icons_v013/icons/exclamation.png" alt="[error]" style="vertical-align: bottom" /> ' .
                                $this->htmlSpecialCharsText(call_user_func_array(array($this, 'translate'), $error)) .
                            '</p>';
                    }
                    foreach ($validator->getWarnings($attributeName) as $warning) {
                        echo '<p class="warning">'.
                                '<img src="/media/famfamfam_silk_icons_v013/icons/error.png" alt="[error]" style="vertical-align: bottom" /> ' .
                                $this->htmlSpecialCharsText(call_user_func_array(array($this, 'translate'), $warning)) .
                            '</p>';
                    }
                endif; ?>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<hr />
<p>
    <?= $this->htmlSpecialCharsText($this->t('idp_debugging_mail_explain')); ?>
</p>
<form method="post">
    <input type="hidden" name="mail" value="true" />
    <input type="submit" value="<?= $this->htmlSpecialCharsAttributeValue($this->t('idp_debugging_mail_button')); ?>" />
</form>
