<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Identity Provider Selectie<?=($metaDataSP['OrganizationDisplayName']?' - ' . $metaDataSP['OrganizationDisplayName']:'')?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow"/>
        <link href="https://espee.surfnet.nl/federate/surfnet/css/screen.css" rel="stylesheet" type="text/css" />
        <link href="https://espee.surfnet.nl/federate/surfnet/css/table.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="/css/ext/jqueryui/1.8.2/themes/base/jquery-ui.css" type="text/css" media="all"/>
        <link rel="stylesheet" href="/css/popup.css" type="text/css" media="all"/>
    </head>
    <body>

        <div class="wrapper">
            <div class="header">
                <a href="http://www.surfnet.nl">
                    <img class="logo" src="https://espee.surfnet.nl/federate/surfnet/img/surfnet_logo.gif" alt="logo" />
                </a>
                <span>SURFconext</span>
                <span class="left"></span>
                <span class="right"></span>
                <img src="https://espee.surfnet.nl/federate/surfnet/img/federatie_header.jpg" alt="header img" />
            </div>
            <div class="main">
                <div class="column content">
                    <div class="item">
                        <span class="h2">
                            Identity Provider Selection <?=($metaDataSP['OrganizationDisplayName']?' - ' . $metaDataSP['OrganizationDisplayName']:'')?>
                        </span>

                        <p>Select your identity provider to sign into this application using SURFconext.
                            If your identity provider is not listed, you may be able to log in with a SURFguest account.

                        </p>

                        <hr />

                        <p>Selecteer je instelling om in te loggen in deze applicatie via SURFconext.
                            Als je instelling niet in de lijst staat, kan je mogelijk inloggen met een SURFguest account.
                        </p>

                        <form method="post" action="<?= $action ?>">
                            <input type=hidden name=ID value="<?= $ID ?>">
                            <p>
                                <select id="idp" name="idp" onkeyup="if (arguments[0]) { if (arguments[0]['keyCode']) { if (arguments[0]['keyCode']===13) { this.form.submit();}}}">
                                <? foreach($idpList as $idp): ?>
                                    <? if (isset($remoteEntities[$idp]['Description']['en'])) { ?>
                                    <option value="<?=$idp?>" <?php if ($idp===$preselectedIdp) echo 'selected="selected"'; ?>>
                                        <?=htmlentities($remoteEntities[$idp]['Description']['nl'])?>
                                    </option>
                                    <? } else { ?>
                                    <option><?= $idp ?></option>
                                    <? } ?>
                                <? endforeach ?>
                                </select>
                            </p>
                            <p>
                                <input type="submit" value="Confirm" />
                            </p>
                        </form>
                    </div>
                </div>
            </div>
            <div class="footer">
                <p>Bezoek ook:</p>
                <ul>
                    <li><a href="http://www.surfnet.nl">SURFnet</a></li>
                </ul>
                <address>
                    <span><strong>SURFnet bv</strong></span>
                    <span>Radboudkwartier 273</span>
                    <span>Postbus 19035</span>
                    <span>3501 DA Utrecht</span>
                    <span>T +31 302 305 305</span>
                    <span>F +31 302 305 329</span>
                    <a href="mailto:help@surfmedia.nl">
                        help@surfmedia.nl
                    </a>
                    <a class="extra" href="http://www.surfnet.nl/nl/pages/copyright.aspx">
                        Copyright
                    </a>
                    <a class="extra" href="http://www.surfnet.nl/nl/pages/disclaimer.aspx">
                        Disclaimer
                    </a>
                </address>
            </div>
        </div>
        <?php if ($preselectedIdp) : ?>
        <div id="dialog" style="display: none;">
            Logging you in to: <br />
            <strong><?php echo $remoteEntities[$preselectedIdp]['Description']['en']; ?></strong>
            <br /><br />
            in: <strong id="secondsRemaining"></strong>
            <br /><br />
            <a id="cancel" href="#" onclick="$('#dialog').dialog('close');">CANCEL</a> (or press ESC)
        </div>
        <? endif; ?>
        <script type="text/javascript" src="/javascript/jquery-1.5.1.min.js"></script>
        <script src="/javascript/jquery-ui-1.8.10.custom.min.js"></script>

        <script type="text/javascript">
            document.getElementById('idp').focus();

            <?php if ($preselectedIdp) : ?>
            (function(){
                var preselectedIdp = <?php echo json_encode($preselectedIdp); ?>;
                var preselectedIdpData = <?php echo json_encode($remoteEntities[$preselectedIdp]); ?>;


                var Timer = function(seconds, onComplete, onTick) {
                    seconds++;
                    var public =  {
                        stopped: false,

                        tick: function() {
                            var that = this;

                            if (seconds-- <= 0) {
                                if (onComplete) {
                                    onComplete();
                                }
                            }
                            else if (!this.stopped) {
                                window.setTimeout(function() {
                                    if (onTick) {
                                        onTick();
                                    }
                                    that.tick();
                                }, 1000);
                            }
                        },

                        getSeconds: function() {
                            return seconds;
                        },

                        stop: function() {
                            this.stopped = true;
                        }

                    };

                    // Start ticking
                    public.tick();
                    return public;
                };

                var countdown = new Timer(5, function() {
                   $('#idp').attr('value', preselectedIdp).parents('form')[0].submit();
                }, function() {
                    $('#secondsRemaining').html(countdown.getSeconds());
                });
                $( "#dialog" ).dialog( {
                    modal: true,
                    dialogClass: "ui-popup",
                    close: function(event, ui) {
                        countdown.stop();
                    }
                });
            }());
            <?php endif; ?>
        </script>
    </body>
</html>
