<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Identity Provider Selectie<?=($metaDataSP['OrganizationDisplayName']?' - ' . $metaDataSP['OrganizationDisplayName']:'')?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow"/>
        <link href="https://espee.surfnet.nl/federate/surfnet/css/screen.css" rel="stylesheet" type="text/css" />
        <link href="https://espee.surfnet.nl/federate/surfnet/css/table.css" rel="stylesheet" type="text/css" />
    </head>
    <body>

        <div class="wrapper">
            <div class="header">
                <a href="http://www.surfnet.nl">
                    <img class="logo" src="https://espee.surfnet.nl/federate/surfnet/img/surfnet_logo.gif" alt="logo" />
                </a>
                <span>SURFconext</span>
                <span class="left"></span>
                <span class="right"></span>
                <img src="https://espee.surfnet.nl/federate/surfnet/img/federatie_header.jpg" alt="header img" />
            </div>
            <div class="main">
                <div class="column content">
                    <div class="item">
                        <span class="h2">
                            Identity Provider Selection <?=($metaDataSP['OrganizationDisplayName']?' - ' . $metaDataSP['OrganizationDisplayName']:'')?>
                        </span>

                        <p>Select your identity provider to sign into this application using SURFconext.
                            If your identity provider is not listed, you may be able to log in with a SURFguest account.

                        </p>

                        <hr />

                        <p>Selecteer je instelling om in te loggen in deze applicatie via SURFconext.
                            Als je instelling niet in de lijst staat, kan je mogelijk inloggen met een SURFguest account.
                        </p>


                        <form method="post" action="<?= $action ?>">
                            <input type=hidden name=ID value="<?= $ID ?>">
                            <p>
                                <select id="idp" name="idp" onkeyup="if (arguments[0]) { if (arguments[0]['keyCode']) { if (arguments[0]['keyCode']===13) { this.form.submit();}}}">
                                <? foreach($idpList as $idp): ?>
                                    <? if (isset($remoteEntities[$idp]['Description']['nl'])) { ?>
                                    <option value="<?=$idp?>"><?=htmlentities($remoteEntities[$idp]['Description']['nl'])?></option>
                                    <? } else { ?>
                                    <option><?= $idp ?></option>
                                    <? } ?>
                                <? endforeach ?>
                                </select>
                            </p>
                            <p>
                                <input type="submit" value="Confirm" />
                            </p>
                        </form>
                    </div>
                </div>
            </div>
            <div class="footer">
                <p>Bezoek ook:</p>
                <ul>
                    <li><a href="http://www.surfnet.nl">SURFnet</a></li>
                </ul>
                <address>
                    <span><strong>SURFnet bv</strong></span>
                    <span>Radboudkwartier 273</span>
                    <span>Postbus 19035</span>
                    <span>3501 DA Utrecht</span>
                    <span>T +31 302 305 305</span>
                    <span>F +31 302 305 329</span>
                    <a href="mailto:help@surfmedia.nl">
                        help@surfmedia.nl
                    </a>
                    <a class="extra" href="http://www.surfnet.nl/nl/pages/copyright.aspx">
                        Copyright
                    </a>
                    <a class="extra" href="http://www.surfnet.nl/nl/pages/disclaimer.aspx">
                        Disclaimer
                    </a>
                </address>
            </div>
        </div>
        <script type="text/javascript">
          document.getElementById('idp').focus();
        </script>
    </body>
</html>
