<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

$lang = $this->language();
$uri = $_SERVER['REQUEST_URI'];
$displayName = $metaDataSP['Name'][$lang] ? $metaDataSP['Name'][$lang] : $metaDataSP['DisplayName'][$lang] ? $metaDataSP['DisplayName'][$lang] : '';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Identity Provider Selection <?=($displayName?' - ' . $displayName : '')?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow"/>
        <link href="/css/ext/jqueryjscrollpane/jquery.jscrollpane.css" rel="stylesheet" type="text/css" />
		<link href="/css/screen.css" rel="stylesheet" type="text/css" />
        <!--[if lt IE 8 ]><link href="https://wayf.surfnet.nl/federate/discovery/css/screen_ie.css" rel="stylesheet" type="text/css" media="screen" /><![endif]-->

    </head>
    <body class="index">
        <form id="IdpListForm" method="post" action="<?= $action ?>">
            <input id="ID" type="hidden" name="ID" value="<?= $ID ?>">
            <input id="Idp" type="hidden" name="idp" value="">
        </form>
        <div id="wrapper">
            <div id="header"><b><font size="4"><?=$displayName?></font></b></div>
            <div id="main">
                <ul class="nav">
                    <li id="help_nav"><a href="#">HELP</a></li>
                    <li id="lang_en"><a href="#">EN</a></li>
                    <li id="lang_nl"><a href="#">NL</a></li>
                </ul>
                <h1> <?php echo $this->t('index_header'); ?></h1>
                <div id="content">
                    <p><?php echo $this->t('index_description', $displayName); ?></p>
                    <?php if ($preselectedIdp) : ?>
                    <div id="IdpSuggestion" class="suggestion">
                    </div>
                    <? endif; ?>
                    <input class="search" id="searchBox" value="<?php echo $this->t('search'); ?>"/>

                    <div class="results">
                        <div id="noResultsMessage" style="display:none">
                            <p class="noresults"><?php echo $this->t('no_results'); ?></p>
                        </div>

                        <div id="scrollViewport">
                            <ul class="thumbs clearfix" id="organisationsContainer"></ul>
                        </div>
                        <ul id="resultTabs" class="tabs">
                            <li class="thumbs active" id="tabThumbs">Thumbnails</li>
                            <li class="list" id="tabList">List</li>
                        </ul>
                    </div>
                </div>
                <div id="help">
                </div>
                <div class="bottom">
                    <p><?php echo $this->t('footer'); ?></p>
                </div>
            </div>
        </div>

        <script id="idpListTemplate" type="text/x-jquery-tmpl">
            <li id="c${ID}" class="${NoAccessClass}"><a alt="${Alt}" href="#"><img src="${Logo}" /><span>${Name}</span>${NoAccess}</a></li>
        </script>
        <script id="idpListSuggestionTemplate" type="text/x-jquery-tmpl">
            <p>
                <a alt="${Alt}" class="${NoAccessClass}" href="#">
                    ${Suggestion}
                    <img class="logo" src="${Logo}" />
                    <span>${Name} ${NoAccess}</span>
                </a>
            </p>
        </script>
        <script type="text/javascript" src="/javascript/jquery-1.5.1.min.js"></script>
        <script type="text/javascript" src="/javascript/jquery.mousewheel.min.js"></script>
        <script type="text/javascript" src="/javascript/jquery.jscrollpane.min.js"></script>
        <script type="text/javascript" src="/javascript/jquery.tmpl.min.js"></script>
        <script type="text/javascript" src="/javascript/keyboardNavigator.js"></script>
        <script type="text/javascript" src="/javascript/typewatch.js"></script>
        <script type="text/javascript" src="/javascript/jquery.cookie.js"></script>
        <script type="text/javascript" src="/javascript/discover.js"></script>

        <script type="text/javascript">

            var discoveryScreen = new Discover();
            discoveryScreen.setLanguage('<?=$lang?>');
            discoveryScreen.setSearchText('<?php echo $this->t('search'); ?>');
            discoveryScreen.setIdpList(<? echo json_encode($idpList); ?>);
            discoveryScreen.setUri('<?=$uri?>');
            <?php if ($preselectedIdp) : ?>
                discoveryScreen.setSelectedEntityId(<? echo json_encode($preselectedIdp); ?>);
            <? endif; ?>

            discoveryScreen.show();
        </script>
    </body>
</html>
