<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

 if (!isset($action)) {
    throw new EngineBlock_Exception('No action given to HTTP Post screen');
}
if (!isset($name)) {
    throw new EngineBlock_Exception('No message type (SAMLRequest or SAMLResponse) given to HTTP Post screen');
}
if (!isset($message)) {
    throw new EngineBlock_Exception('No message given to HTTP Post screen');
}

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->setLayout('form');

// Set Layout properties
$layout->title = $layout->title. ' - '. $this->t('post_data');
$layout->header = $layout->title;
$layout->subheader = $this->t('post_data');
$layout->footerText = $this->t('footer');

if (!$trace) {
    $layout->getView()->inlineScript()->appendScript("
    $(document).ready(function() {
        $('#ProcessForm').submit();
    });");
}

$layout->getView()->inlineScript()->appendScript("
$(document).ready(function() {
    $('#submitbutton').focus();
});");

?>
        <noscript>
            <p>
                <strong><?php echo $this->t('note'); ?>:</strong>
                    <?php echo $this->t('note_no_script'); ?>
            </p>
        </noscript>
        <p><?php echo $this->t('processing'); ?></p>
        <form id="ProcessForm" method="post" action=" <?= $action ?>">
            <input type="hidden" name="<?= $name ?>" value="<?= $message ?>" />

            <?= $xtra ?>

            <noscript><input type="submit" value="Submit" /></noscript>

            <? if ($trace): ?>
            <input id="submitbutton" type="submit" value="Submit" />
            <div class="trace-wrapper">
                <pre>
                    <?= $trace ?>
                </pre>
            </div>
            <? endif; ?>

        </form>
