<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

 if (!isset($action)) {
    throw new EngineBlock_Exception('No action given to HTTP Post screen');
}
if (!isset($name)) {
    throw new EngineBlock_Exception('No message type (SAMLRequest or SAMLResponse) given to HTTP Post screen');
}
if (!isset($message)) {
    throw new EngineBlock_Exception('No message given to HTTP Post screen');
}

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->setLayout('empty');

// Set Layout properties
$layout->title = $layout->title. ' - '. $this->t('post_data');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow"/>
        <title><?php echo $layout->title; ?></title>
        <style type="text/css">
        body {
            color:#333;
            font: 12px/17px Arial, Helvetica, sans-serif;
            padding: 0;
            margin: 0;
            background: #e7e7e7;
        }
        p {
            padding: 0;
            margin: 10px 0 0 10px;
        }
        </style>
    </head>
    <body <?php if (!$trace): ?>onload="document.forms[0].submit()"<?php endif; ?>>
        <noscript>
            <p>
                <strong><?php echo $this->t('note'); ?>:</strong>
                    <?php echo $this->t('note_no_script'); ?>
            </p>
        </noscript>
        <p><?php echo $this->t('processing'); ?></p>
        <form id="ProcessForm" method="post" action="<?php echo $action ?>">
            <input type="hidden" name="<?php echo $name ?>" value="<?php echo $message ?>" />

            <?php echo $xtra ?>

            <noscript><input type="submit" value="Submit" /></noscript>

            <?php if ($trace): ?>
            <input id="submitbutton" type="submit" value="Submit" />
            <pre>
                <?php echo $trace ?>
            </pre>
            <script type="text/javascript">
                document.getElementById('submitbutton').focus();
            </script>
            <?php endif; ?>

        </form>
    </body>
</html>
