<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>SURFnet Collaboration Infrastructure EngineBlock - Cron Page</title>
    </head>
    <body>
        <h1>Welcome to SURFnet Collaboration Infrastructure EngineBlock Cron Page!</h1>
        <h2>Cron URLs</h2>
        <ul>
            <li>
                <a href="/cron/deprovision">
                    /cron/deprovision
                </a>
                <br />
                <p>Deprovision users based on the configuration values stored. The user is removed from the LDAP and removed from any group in Grouper<br />
                This defaults to:
                </p>
                <ul>
                    <li>First warning 4 weeks before account deprovisioning to the user and to the group members of the groups for which the user is the only admin.</li>
                    <li>Second warning 2 weeks before account deprovisioning to the user and to the group members of the groups for which the user is the only admin.</li>
                    <li>Account deprovisioning</li>
                </ul>
                <br />
                <strong>Example:</strong>
                <a href="/cron/deprovision">
                    /cron/deprovision
                </a>
            </li>
        </ul>
    </body>
</html>
