<?php

/**
 * See OpenConext-engineblock/library/EngineBlock/Corto/Module/Service/ProvideConsent.php#84
 */
use OpenConext\Component\EngineBlockMetadata\Entity\IdentityProvider;
use OpenConext\Component\EngineBlockMetadata\Entity\ServiceProvider;

if (!isset($action)) {
    throw new EngineBlock_View_Exception('No Consent action given to consent screen');
}
if (!isset($ID)) {
    throw new EngineBlock_View_Exception('No ID given to consent screen');
}
if (!isset($attributes)) {
    throw new EngineBlock_View_Exception('No Attributes given to consent screen');
}
if (!isset($attribute_sources)) {
    throw new EngineBlock_View_Exception('No attributes sources given to consent screen');
}
if (!isset($sp) || !$sp instanceof ServiceProvider) {
    throw new EngineBlock_View_Exception('No SP information given to consent screen');
}
if (!isset($idp) || !$idp instanceof IdentityProvider) {
    throw new EngineBlock_View_Exception('No IdP information given to consent screen');
}
/** @var EngineBlock_View $this */

$locale = $this->getLocale();

// @todo move to entity (see also duplicate in discover.phtml)
$spName = '';
if ($locale === 'nl') {
    $spName = $sp->nameNl;
}
if (empty($spName)) {
    $spName = $sp->nameEn;
}
if (empty($spName)) {
    $spName = $sp->entityId;
}

$idpName = '';
if ($locale === 'nl') {
    $idpName = $idp->nameNl;
}
if (empty($idpName)) {
    $idpName = $idp->nameEn;
}
if (empty($idpName)) {
    $idpName = $idp->entityId;
}

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();

// Set different layout
$layout->setLayout('default');

// Set Layout variables
$layout->use_header = false;
$layout->title      = $layout->title . ' - '. $this->t('consent_header_title', $spName);

?>

<div class="box">
  <div class="mod-content consent">
    <header>
      <h1><?= $this->t('consent_header_title', $spName); ?></h1>
      <p><?= $this->t('consent_header_text', $spName); ?></p>
    </header>

    <section class="privacy">
      <h2><?= $this->t('consent_privacy_title', $spName); ?></h2>
      <?php if (isset($sp->termsOfServiceUrl)) : ?>
        <a href="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($sp->termsOfServiceUrl); ?>" target="_blank"><?= $this->t('consent_privacy_link'); ?></a>
      <?php endif; ?>
    </section>

    <section class="attributes">
      <table class="comp-table attributes">
        <?php $attributesBySource = $this->sortByDisplayOrder($attributes, $attribute_sources) ?>
        <?php foreach ($attributesBySource as $attributeSource => $attributes): ?>
        <tbody data-attr-source="<?=EngineBlock_View::htmlSpecialCharsText($attributeSource) ?>">
          <tr class="source-info">
            <td colspan="2">
              <?php if ($attributeSource !== 'idp'): ?>
                <img width="30" height="30" src="<?= $this->getAttributeSourceLogoUrl($attributeSource); ?>" alt="" />
                <h2><?= $this->getAttributeSourceDisplayName($attributeSource); ?></h2>
              <?php else:?>
                <?php if (isset($idp->logo)): ?>
                  <img width="30" height="30" src="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($idp->logo->url); ?>" alt="" />
                <?php else: ?>
                  <img width="30" height="30" src="/images/placeholder.png" alt="" />
                <?php endif; ?>
                <h2><?= EngineBlock_View::htmlSpecialCharsAttributeValue($idpName); ?></h2>
              <?php endif ?>
              <a href="#" data-slidein="correction-<?= EngineBlock_View::htmlSpecialCharsAttributeValue($attributeSource); ?>"><?= $this->t('consent_attributes_correction_link'); ?></a>
            </td>
          </tr>

          <?php foreach ($attributes as $attributeIdentifier => $attributeValues) : ?>
          <?php
          // Attempt to get the short name for the attribute, else use the identifier
          $attributeShortName = $this->getAttributeName($attributeIdentifier, $locale);
          if (trim($attributeShortName) === '') {
            $attributeShortName = $attributeIdentifier;
          }
          ?>
          <tr>
            <td class="attr-name" data-identifier="<?=EngineBlock_View::htmlSpecialCharsText($attributeIdentifier) ?>">
              <?=EngineBlock_View::htmlSpecialCharsText($attributeShortName) ?>
            </td>
            <td class="attr-value">
              <?php /** Single attribute value */ if (count($attributeValues)==1) : ?>
              <a class="help tooltip" title="<?=EngineBlock_View::htmlSpecialCharsText($attributeIdentifier); ?>" href="#">
                <?=EngineBlock_View::htmlSpecialCharsText($attributeValues[0]);?>
              </a>
              <?php /** Multiple attribute values */ else: ?>
              <ul>
                <?php foreach ($attributeValues as $value) : ?>
                <li>
                  <a class="help tooltip" title="<?=EngineBlock_View::htmlSpecialCharsText($attributeIdentifier); ?>" href="#">
                    <?=EngineBlock_View::htmlSpecialCharsText($value); ?>
                  </a>
                </li>
                <?php endforeach ?>
              </ul>
              <?php endif ?>
            </td>
          </tr>
          <?php endforeach ?>
          <tr class="toggle-attributes">
            <td colspan="2">
              <a href="#">
                <?= $this->t('consent_attributes_show_all'); ?>
              </a>
            </td>
          </tr>
          <tr class="separator">
            <td colspan="2"></td>
          </tr>
        </tbody>
        <?php endforeach ?>
      </table>
    </section>

    <section>
      <h2><?= $this->t('consent_buttons_title'); ?></h2>
      <!-- YES -->
      <form id="accept" method="post" action="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($action); ?>">
        <input type="hidden" name="ID"      value="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($ID); ?>">
        <input type="hidden" name="consent" value="yes" />
        <input id="accept_terms_button"
          class="submit c-button"
          type="submit"
          value="<?= $this->t('consent_buttons_ok', $spName); ?>"
        />
      </form>

      <!-- NO -->
      <a id="decline-terms" class="reject c-button c-button-link" href="#" data-slidein="reject">
        <?= $this->t('consent_buttons_nok'); ?>
      </a>
    </section>

    <footer>
      <p>
        <?php if ($consent_count === 0): ?>
          <?= $this->t('consent_footer_text_first_consent'); ?>
        <?php elseif ($consent_count === 1): ?>
          <?= $this->t('consent_footer_text_singular'); ?>
        <?php else: ?>
          <?= $this->t('consent_footer_text_plural', $consent_count); ?>
        <?php endif; ?>
      </p>
    </footer>
  </div>
</div>
<?php require(__DIR__ . '/consent-slidein-reject.phtml'); ?>
<?php foreach (array_keys($attributesBySource) as $attributeSource): ?>
  <?php require(__DIR__ . '/consent-slidein-correction.phtml'); ?>
<?php endforeach; ?>
<?php require(__DIR__ . '/consent-slidein-about.phtml'); ?>
