<div class="slidein reject">
  <div class="mod-content">
    <a class="close" href="#"><?= $this->t('slidein_close'); ?></a>
    <section>
      <?php if (isset($idp_support->emailAddress)): ?>
        <?= $this->t('consent_slidein_reject_text', $idp_support->emailAddress); ?>
      <?php else: ?>
        <?= $this->t('consent_slidein_reject_text_no_support'); ?>
      <?php endif; ?>
    </section>
  </div>
</div>
