<div class="slidein correction-<?= EngineBlock_View::htmlSpecialCharsAttributeValue($attributeSource); ?>">
  <div class="mod-content">
    <a class="close" href="#"><?= $this->t('slidein_close'); ?></a>
    <section>
      <h1><?= $this->t('consent_slidein_correction_title'); ?></h1>
      <?php if ($attributeSource === 'idp'): ?>
        <p><?= $this->t('consent_slidein_correction_text_idp'); ?></p>
        <?php require(__DIR__ . '/consent-slidein-contact-details.phtml'); ?>
      <?php else: ?>
        <p><?= $this->t('consent_slidein_correction_text_aa'); ?></p>
      <?php endif; ?>
    </section>
  </div>
</div>
