<?php

/**
 * See OpenConext-engineblock/library/EngineBlock/Corto/Module/Service/ProvideConsent.php#84
 */
use OpenConext\Component\EngineBlockMetadata\Entity\IdentityProvider;
use OpenConext\Component\EngineBlockMetadata\Entity\ServiceProvider;

if (!isset($action)) {
    throw new EngineBlock_View_Exception('No Consent action given to consent screen');
}
if (!isset($ID)) {
    throw new EngineBlock_View_Exception('No ID given to consent screen');
}
if (!isset($attributes)) {
    throw new EngineBlock_View_Exception('No Attributes given to consent screen');
}
if (!isset($attribute_sources)) {
    throw new EngineBlock_View_Exception('No attributes sources given to consent screen');
}
if (!isset($sp) || !$sp instanceof ServiceProvider) {
    throw new EngineBlock_View_Exception('No SP information given to consent screen');
}
if (!isset($idp) || !$idp instanceof IdentityProvider) {
    throw new EngineBlock_View_Exception('No IdP information given to consent screen');
}
/** @var EngineBlock_View $this */

$locale = $this->getLocale();

// @todo move to entity (see also duplicate in discover.phtml)
$spName = '';
if ($locale === 'nl') {
    $spName = $sp->nameNl;
}
if (empty($spName)) {
    $spName = $sp->nameEn;
}
if (empty($spName)) {
    $spName = $sp->entityId;
}

$idpName = '';
if ($locale === 'nl') {
    $idpName = $idp->nameNl;
}
if (empty($idpName)) {
    $idpName = $idp->nameEn;
}
if (empty($idpName)) {
    $idpName = $idp->entityId;
}

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();

// Set different layout
$layout->setLayout('default');

// Set Layout variables
$layout->use_header = false;
$layout->title      = $layout->title . ' - '. $this->t('consent_header', $spName);
$layout->subheader  = $this->t('consent_subheader', $spName);

/** @var $view Zend_View */
$view = $layout->getView();
/** @var $inlineScriptHelper Zend_View_Helper_InlineScript */
$inlineScriptHelper = $view->getHelper('InlineScript');
$inlineScriptHelper->appendScript('$("#accept_terms_button").focus();');
$inlineScriptHelper->appendScript('
(function() {
    var d = new Discover();
    d.linkHelp();
' . (isset($_POST['show-help']) && $_POST['show-help'] === 'yes' ? 'd.showHelp(0)' : '') .
' })();');
?>

<div class="box">
  <div class="mod-content">
    <header>
      <img src="/images/user.svg" alt="user" />
      <h1><?= $this->t('consent_header_info'); ?></h1>
    </header>

    <p>
        <?= $this->t('consent_sp_idp_info', $spName, $idpName); ?>
    </p>

    <div class="l-overflow">
      <?php $attributesBySource = $this->sortByDisplayOrder($attributes, $attribute_sources) ?>
      <?php foreach ($attributesBySource as $attributeSource => $attributes) : ?>
        <?php if ($attributeSource !== 'idp'): ?>
          <p>
            <?= $this->t('consent_aggregated_attributes_info', $spName, $this->getAttributeSourceDisplayName($attributeSource)); ?>
          </p>
        <?php endif ?>
        <table class="comp-table" data-attr-source="<?php print EngineBlock_View::htmlSpecialCharsText($attributeSource); ?>">
          <?php foreach ($attributes as $attributeIdentifier => $attributeValues) : ?>

            <?php
            // Attempt to get the short name for the attribute, else use the identifier
            $attributeShortName = $this->getAttributeName($attributeIdentifier, $locale);
            if (trim($attributeShortName) === '') {
                $attributeShortName = $attributeIdentifier;
            }
            ?>
            <tr>
              <td class="strong" data-identifier="<?= $attributeIdentifier ?>">
                <?=EngineBlock_View::htmlSpecialCharsText($attributeShortName) ?>
              </td>
              <td>
                <?php /** Single attribute value */ if (count($attributeValues)==1) : ?>
                  <?=EngineBlock_View::htmlSpecialCharsText($attributeValues[0]);?>
                <?php /** Multiple attribute values */ else: ?>
                  <ul>
                    <?php foreach ($attributeValues as $value) : ?>
                      <li><?=EngineBlock_View::htmlSpecialCharsText($value); ?></li>
                    <?php endforeach ?>
                  </ul>
                <?php endif ?>
              </td>
            </tr>
          <?php endforeach ?>
        </table>
      <?php endforeach ?>
    </div>

    <div id="approve">
      <!-- YES -->
      <form id="accept" method="post" action="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($action); ?>">
          <input type="hidden" name="ID"      value="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($ID); ?>">
          <input type="hidden" name="consent" value="yes" />

        <p>
          <input id="accept_terms_button"
                 class="submit c-button"
                 type="submit"
                 value="<?= $this->t('consent_accept'); ?>"
                 />
        </p>
      </form>

      <!-- NO -->
      <form id="reject" method="post" action="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($action); ?>">
              <input type="hidden" name="ID"      value="<?=EngineBlock_View::htmlSpecialCharsAttributeValue($ID); ?>">
              <input type="hidden" name="consent" value="no" />
        <p>
              <a id="decline_terms_button" class="c-button c-button-link" href="#" onclick="document.getElementById('reject').submit();">
                  <?= $this->t('consent_decline'); ?>
              </a>
        </p>
      </form>
    </div>

    <p class="grey"><?= $this->t('consent_notice'); ?></p>

    <?php if (isset($sp->termsOfServiceUrl)) : ?>
        <?= $this->t('sp_terms_of_service', $spName, $sp->termsOfServiceUrl); ?>
    <?php endif; ?>
  </div>
</div>
