<?php

use OpenConext\Component\EngineBlockMetadata\Entity\ServiceProvider;

/**
 * Injected variables;
 * @var EngineBlock_View $this
 * @var ServiceProvider $metaDataSP
 * @var array $idpList
 * @var string $action
 * @var string $ID
 * @var string $preselectedIdp
 */

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->assign('subheader', 'Log in to ');

// Determine the selected language, default to english
if (isset($_GET['lang'])) {
    $lang = $_GET['lang'];
}
else if (isset($_COOKIE['lang'])) {
    $lang = $_COOKIE['lang'];
}
else {
    $lang = 'en';
}

// Guard against unsupported languages.
if (!in_array($lang, array('nl','en'))) {
    $lang = 'en';
}

// @todo move to entity (see also duplicate in consent.phtml)
$spDisplayName = '';
if ($lang === 'nl') {
    if ($metaDataSP->nameNl) {
        $spDisplayName = $metaDataSP->nameNl;
    }
    else if ($metaDataSP->displayNameNl) {
        $spDisplayName = $metaDataSP->displayNameNl;
    }
    else if ($metaDataSP->nameEn) {
        $spDisplayName = $metaDataSP->nameEn;
    }
    else if ($metaDataSP->displayNameEn) {
        $spDisplayName = $metaDataSP->displayNameEn;
    }
}
else {
    if ($metaDataSP->nameEn) {
        $spDisplayName = $metaDataSP->nameEn;
    }
    else if ($metaDataSP->displayNameEn) {
        $spDisplayName = $metaDataSP->displayNameEn;
    }
    else if ($metaDataSP->nameNl) {
        $spDisplayName = $metaDataSP->nameNl;
    }
    else if ($metaDataSP->displayNameNl) {
        $spDisplayName = $metaDataSP->displayNameNl;
    }
}

$preselectedIdpData = array();
if ($preselectedIdp) {
    foreach ($idpList as $idp) {
        if ($idp['EntityID'] === $preselectedIdp) {
            $preselectedIdpData = $idp;
            break;
        }
    }
}

$layout->assign('greenHeader', $spDisplayName);
$layout->assign('helpLink', '/authentication/idp/help-discover?lang=' . $lang);
?>

<form class="mod-search" method="post" action="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($action); ?>">
  <input placeholder="<?= $this->t('search'); ?>" type="search" tabindex="0" autofocus="autofocus" class="mod-search-input active nav-el">
  <div class="results">

    <?php if (count($preselectedIdpData)): ?>
    <h2>Last time you chose</h2>
    <a class="result active nav-el" href="#" tabindex="-1" data-idp="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($preselectedIdpData['EntityID']); ?>">
      <img class="logo" src="<?= $preselectedIdpData['Logo'] ?>" />
      <h3><?= EngineBlock_View::htmlSpecialCharsAttributeValue($preselectedIdpData['Name_' . $lang]); ?></h3>
      <div class="c-button outline narrow">Press enter to select</div>
    </a>

    <h2>Other results</h2>
    <?php endif; ?>
    <?php foreach ($idpList as $idp) : ?>
      <a class="result active nav-el" href="#" tabindex="-1" data-idp="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($idp['EntityID']); ?>">
        <img class="logo" src="<?= $idp['Logo'] ?>" />
        <h3><?= EngineBlock_View::htmlSpecialCharsAttributeValue($idp['Name_' . $lang]); ?></h3>
        <div class="c-button outline narrow">Press enter to select</div>
      </a>
    <?php endforeach; ?>

  </div>
  <input type="hidden" name="ID" value="<?= EngineBlock_View::htmlSpecialCharsAttributeValue($ID); ?>" />
  <input type="hidden" id="form-idp" name="idp" value="" />
</form>
