<?php

if (!isset($action)) {
    throw new EngineBlock_View_Exception('No action given to HTTP Post screen');
}
if (!isset($name)) {
    throw new EngineBlock_View_Exception('No message type (SAMLRequest or SAMLResponse) given to HTTP Post screen');
}
if (!isset($message)) {
    throw new EngineBlock_View_Exception('No message given to HTTP Post screen');
}

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->setLayout('empty');

// Set Layout properties
$layout->title = $layout->title. ' - '. $this->t('post_data');
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow"/>
        <title><?= $layout->title; ?></title>
        <link href="/stylesheets/application.css" rel="stylesheet" type="text/css" />
    </head>
    <body class="index" <?php if (!$trace): ?>onload="document.forms[0].submit()"<?php endif; ?>>
      <div class="mod-redirect">
        <img src="/images/spinner.svg" />
        <h1><?= $this->t('processing'); ?></h1>
        <p><?= $this->t('processing_waiting'); ?></p>
        <p>Taking too long? <a href="javascript:history.back(-2)"><?= $this->t('go_back'); ?></a>.</p>
        <noscript>
          <p>
            <strong><?= $this->t('note'); ?>:</strong>
            <?= $this->t('note_no_script'); ?>
          </p>
        </noscript>
      </div>
        <form id="ProcessForm" method="post" action="<?= $action ?>">
            <input type="hidden" name="<?= $name ?>" value="<?= $message ?>" />

            <?= $xtra ?>

            <noscript><input type="submit" value="Submit" /></noscript>

            <?php if ($trace): ?>
            <input id="submitbutton" type="submit" value="Submit" />
            <pre>
                <?= $trace ?>
            </pre>
            <script type="text/javascript">
                document.getElementById('submitbutton').focus();
            </script>
            <?php endif; ?>

        </form>
    </body>
</html>
