services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#    OpenConext\EngineBlockFunctionalTestingBundle\Features\Context\:
#        resource: '../src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/*'
#        tags: [ 'fob.context' ]

#    OpenConext\EngineBlockFunctionalTestingBundle\Features\Context\EngineBlockContext:
#        arguments:
#            serviceRegistry: '@engineblock.functional_testing.fixture.service_registry'
#            engineBlock: '@engineblock.functional_testing.service.engine_block'
#            mockSpRegistry: '@engineblock.mock_entities.sp_registry'
#            mockIdpRegistry: '@engineblock.mock_entities.idp_registry'
#            features: '@engineblock.functional_testing.fixture.features'
#            pdpClient: '@engineblock.functional_testing.fixture.pdp_client'
#            authenticationLoopGuard: '@engineblock.functional_testing.fixture.authentication_loop_guard'
#            attributeAggregationClient: '@engineblock.functional_testing.fixture.attribute_aggregation_client'
#        public: true
