<?php
define('PARTIAL_DIR', __DIR__ . '/partials/');
require PARTIAL_DIR . 'header-start.php';
?>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="/css/ext/jqueryjscrollpane/jquery.jscrollpane.css" rel="stylesheet" type="text/css" />
        <link href="/css/ext/jqueryui/1.8.16/custom-theme/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css" />
        <link href="/css/wide/screen.css" rel="stylesheet" type="text/css" />
        <!--[if lt IE 8 ]>
        <link href="/css/wide/screen_ie.css" rel="stylesheet" type="text/css" media="screen" />
        <![endif]-->

        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body class="index">
        <div class="wrapper">
            <div class="header" style="font-weight: bold; font-size: large">
                <?php echo $this->layout()->header; ?>
                <span class="logo">
                    <img src="/media/surfconext.png" alt="SURFconext">
                </span>
            </div>

            <div id="Tabs" class="main">
                <ul>
                <?php foreach ($this->layout()->tabs as $id => $tab) { ?>
                    <li><a href="#<?php echo $id; ?>"><?php echo $tab; ?></a></li>
                <?php } ?>
                </ul>

                <?php require PARTIAL_DIR . 'nav.php'; ?>

                <?php echo $this->layout()->content; ?>

                <div class="bottom">
                    <p>
                        <hr />
                        <?php echo $this->layout()->footerText; ?>
                    </p>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="/javascript/jquery-1.5.1.min.js"></script>
        <script type="text/javascript" src="/javascript/jquery-ui-1.8.16.custom.min.js"></script>
        <script>
            $(document).ready(function() {
                $('#Tabs').tabs();

                $('ul.nav>li').live('click', function(e) {
                    e.preventDefault();
                    var href = $(this).find('a').attr('href');
                    document.location = '/' + href + $('div#Tabs li.ui-tabs-selected>a').attr('href');
                });
            });
        </script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
