<?php
define('PARTIAL_DIR', __DIR__ . '/partials/');
require PARTIAL_DIR . 'header-start.php';
?>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="/css/ext/jqueryjscrollpane/jquery.jscrollpane.css" rel="stylesheet" type="text/css" />
        <link href="/css/responsive/screen.css" rel="stylesheet" type="text/css" />

        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body class="index">
        <div id="wrapper">
            <div id="header"><b><font size="4"><?php echo htmlentities($this->layout()->header, 0, "UTF-8"); ?></font></b></div>
            <div id="main">

                <?php require PARTIAL_DIR . 'nav.php'; ?>

                <h1><?php echo htmlentities($this->layout()->subheader, 0, "UTF-8"); ?></h1>

                <?php echo $this->layout()->content; ?>

                <div class="bottom">
                    <p>
                        <hr />
                        <?php echo $this->layout()->footerText; ?>
                    </p>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="/javascript/jquery-1.5.1.min.js"></script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
