<?php

$SAMLResponse = $_POST['SAMLResponse'];

define('PARTIAL_DIR', __DIR__ . '/partials/');
require PARTIAL_DIR . 'header-start.php';
?>
        <meta name="viewport" content="width=device-width"/>

        <?php echo EngineBlock_ApplicationSingleton::getInstance()->getDiContainer()->getAssetManager()->getCss(); ?>

        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div id="wrapper">
            <!-- MAIN BOX -->
            <div id="main">

                <!-- Language selection -->
                <form id="LangForm" action="" method="post">
                    <div>
                        <input type="hidden" name="SAMLResponse" value="<?=$SAMLResponse; ?>" />
                        <input type="hidden" name="lang" id="LangVar" />
                        <input type="hidden" name="show-help" id="showHelp" />
                    </div>
                    <ul class="nav top">
                        <li id="help_nav">
                            <a href="#" data-help-type="consent">HELP</a>
                        </li>
                        <li class="<?php if ($lang==='en'): ?>active<?php endif; ?>">
                            <a id="SubmitEnForm" href="#">en</a>
                        </li>
                        <li class="<?php if ($lang==='nl'): ?>active<?php endif; ?>">
                            <a id="SubmitNlForm" href="#">nl</a>
                        </li>
                    </ul>
                </form>

                <!-- Subheader -->
                <h1></h1>

                <!-- Main content -->
                <div id="content" class="centered">
                    <?php echo $this->layout()->content; ?>
                </div>

                <!-- Help container (content injected with AJAX) -->
                <div id="help" style="display: none">
                </div>

                <!-- Footer -->
                <div class="bottom">
                    <p>
                        <hr />
                        <?php echo $this->layout()->footerText; ?>
                    </p>
                </div>
            </div>
        </div>

        <!-- JAVSCRIPT -->
        <?php echo EngineBlock_ApplicationSingleton::getInstance()->getDiContainer()->getAssetManager()->getJs(); ?>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#SubmitEnForm').click(function(e) {
                    e.preventDefault();
                    $('#showHelp').attr('value', $('#help').is(':visible') ? 'yes' : 'no');
                    $('#LangVar').attr('value', 'en');
                    $('#LangForm').submit();
                });

                $('#SubmitNlForm').click(function(e) {
                    e.preventDefault();
                    $('#showHelp').attr('value', $('#help').is(':visible') ? 'yes' : 'no');
                    $('#LangVar').attr('value', 'nl');
                    $('#LangForm').submit();
                });
            });
        </script>
        <?php echo $this->inlineScript(); ?>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                $('#faq h4').next().toggle();
                $('#faq h4').click(function() {
                    $(this).next().toggle('slow');
                    return false;
                }).next().hide();
            });
        </script>
    </body>
</html>
