<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

$SAMLResponse = $_POST['SAMLResponse'];

// Language stuff
$lang = 'en';
if (isset($_POST['lang'])) {
    $lang = $_POST['lang'];
} elseif (isset($_COOKIE['lang'])) {
    $lang = $_COOKIE['lang'];
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow"/>

        <title><?php echo $this->layout()->title;?></title>

        <link href="<?php echo EngineBlock_View::staticUrl(); ?>/css/ext/jqueryjscrollpane/jquery.jscrollpane.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo EngineBlock_View::staticUrl(); ?>/css/responsive/screen.css" rel="stylesheet" type="text/css" media="screen"/>
        <link href="<?php echo EngineBlock_View::staticUrl(); ?>/css/responsive/narrow.css" rel="stylesheet" type="text/css" media="only screen and (max-width: 1000px)"/>
        <!--[if lt IE 8 ]>
        <link href="<?php echo EngineBlock_View::staticUrl(); ?>/css/responsive/screen_ie.css" rel="stylesheet" type="text/css" media="screen" />
        <![endif]-->

        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body class="index">
        <div class="wrapper">
            <div class="header" style="font-weight: bold; font-size: large">
                <?php echo $this->layout()->header; ?>
                <span class="logo">
                    <img src="<?php echo EngineBlock_View::staticUrl(); ?>/media/surfconext.png" alt="SURFconext">
                </span>
            </div>

            <div class="main">
                <!-- Language selection -->
                <form id="LangForm" method="post">
                    <input type="hidden" name="SAMLResponse" value="<?=$SAMLResponse; ?>" />
                    <input type="hidden" name="lang" id="LangVar" />
                    <ul class="nav">
                        <li class="<?php if ($lang==='en'): ?>active<?php endif; ?>">
                            <a id="SubmitEnForm" href="#">en</a>
                        </li>
                        <li class="<?php if ($lang==='nl'): ?>active<?php endif; ?>">
                            <a id="SubmitNlForm" href="#">nl</a>
                        </li>
                    </ul>
                </form>

                <h1><?php echo $this->layout()->subheader; ?></h1>

                <?php echo $this->layout()->content; ?>

                <div class="bottom">
                    <p>
                        <hr />
                        <?php echo $this->layout()->footerText; ?>
                    </p>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="<?php echo EngineBlock_View::staticUrl(); ?>/javascript/jquery-1.5.1.min.js"></script>
        <script src="<?php echo EngineBlock_View::staticUrl(); ?>/javascript/jquery.mediaqueries.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#SubmitEnForm').click(function(e) {
                    e.preventDefault();
                    $('#LangVar').attr('value', 'en');
                    $('#LangForm').submit();
                });

                $('#SubmitNlForm').click(function(e) {
                    e.preventDefault();
                    $('#LangVar').attr('value', 'nl');
                    $('#LangForm').submit();
                });
            });
        </script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
