<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

$SAMLResponse = $_POST['SAMLResponse'];

define('PARTIAL_DIR', __DIR__ . '/partials/');
require PARTIAL_DIR . 'header-start.php';
?>
        <meta name="viewport" content="width=device-width"/>

        <link href="/css/ext/jqueryjscrollpane/jquery.jscrollpane.css" rel="stylesheet" type="text/css" />
        <link href="/css/responsive/screen.css" rel="stylesheet" type="text/css" media="screen"/>

        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div id="wrapper">
            <!-- MAIN BOX -->
            <div id="main">

                <!-- Language selection -->
                <form id="LangForm" action="" method="post">
                    <div>
                        <input type="hidden" name="SAMLResponse" value="<?=$SAMLResponse; ?>" />
                        <input type="hidden" name="lang" id="LangVar" />
                        <input type="hidden" name="show-help" id="showHelp" />
                    </div>
                    <ul class="nav">
                        <li id="help_nav">
                            <a href="#">help</a>
                        </li>
                        <li class="<?php if ($lang==='en'): ?>active<?php endif; ?>">
                            <a id="SubmitEnForm" href="#">en</a>
                        </li>
                        <li class="<?php if ($lang==='nl'): ?>active<?php endif; ?>">
                            <a id="SubmitNlForm" href="#">nl</a>
                        </li>
                    </ul>
                </form>

                <!-- Subheader -->
                <h1><?php echo $this->layout()->subheader; ?></h1>

                <!-- Main content -->
                <div id="content">
                    <?php echo $this->layout()->content; ?>
                </div>

                <!-- Help container (content injected with AJAX) -->
                <div id="help" style="display: none">
                </div>

                <!-- Footer -->
                <div class="bottom">
                    <p>
                        <hr />
                        <?php echo $this->layout()->footerText; ?>
                    </p>
                </div>
            </div>
        </div>

        <!-- JAVSCRIPT -->
        <script type="text/javascript" src="/javascript/jquery-1.5.1.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#SubmitEnForm').click(function(e) {
                    e.preventDefault();
                    $('#showHelp').attr('value', $('#help').is(':visible') ? 'yes' : 'no');
                    $('#LangVar').attr('value', 'en');
                    $('#LangForm').submit();
                });

                $('#SubmitNlForm').click(function(e) {
                    e.preventDefault();
                    $('#showHelp').attr('value', $('#help').is(':visible') ? 'yes' : 'no');
                    $('#LangVar').attr('value', 'nl');
                    $('#LangForm').submit();
                });
            });
        </script>
        <?php echo $this->inlineScript(); ?>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                $('#faq h4').next().toggle();
                $('#faq h4').click(function() {
                    $(this).next().toggle('slow');
                    return false;
                }).next().hide();
            });
        </script>
    </body>
</html>
