<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */

// Language stuff
$lang = 'en';
if (isset($_GET['lang'])) {
    $lang = $_GET['lang'];
} elseif (isset($_COOKIE['lang'])) {
    $lang = $_COOKIE['lang'];
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow"/>
        <meta name="viewport" content = "width = device-width, initial-scale = 0.6, minimum-scale = 0.1, maximum-scale = 5" />


        <title><?php echo $this->layout()->title; ?></title>

        <link href="/css/ext/jqueryjscrollpane/jquery.jscrollpane.css" rel="stylesheet" type="text/css" />
        <link href="/css/narrow/screen.css" rel="stylesheet" type="text/css" />
        <link href="/css/error.css" rel="stylesheet" type="text/css" media="screen" />

        <!--[if lt IE 8 ]>
        <link href="/css/narrow/screen_ie.css" rel="stylesheet" type="text/css" media="screen" />
        <![endif]-->

        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

    </head>
    <body class="index">
        <div id="wrapper">
            <div id="header">
                <h3><?php echo $this->layout()->header; ?></h3>
            </div>
            <div id="main">
                <!-- Language selection -->
                <ul class="nav">
                    <li id="help_nav"><a href="#">HELP</a></li>
                    <li class="<?php if ($lang==='en'): ?>active<?php endif; ?>">
                        <a href="<?php echo htmlspecialchars(EngineBlock_View::setLanguage('en')); ?>">EN</a>
                    </li>
                    <li class="<?php if ($lang==='nl'): ?>active<?php endif; ?>">
                        <a href="<?php echo htmlspecialchars(EngineBlock_View::setLanguage('nl')); ?>">NL</a>
                    </li>
                </ul>
                <h1><?php echo $this->layout()->subheader; ?></h1>

                <?php echo $this->layout()->content; ?>

                <div class="bottom">
                    <hr />
                    <p>
                        <?php echo $this->layout()->footerText; ?>
                    </p>
                </div>
            </div>
        </div>

        <script id="idpListTemplate" type="text/x-jquery-tmpl">
            <li id="c${ID}" class="${NoAccessClass}"><a alt="${Alt}" href="#"><img src="${Logo}" /><span>${Name}</span>${NoAccess}</a></li>
        </script>
        <script id="idpListSuggestionTemplate" type="text/x-jquery-tmpl">
            <p>
                <p>${Suggestion}</p>
                <div class="suggestion-box">
                    <a id="SuggestionLink" alt="${Alt}" class="${NoAccessClass}" href="#">
                        <img class="logo" alt="" src="${Logo}" />
                        <span class="title">${Name} ${NoAccess}</span>
                    </a>
                </div>
            </p>
        </script>
        <script type="text/javascript" src="/javascript/jquery-1.5.1.min.js"></script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
