<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */
?>
<html>
<head></head>
<body>
<table>
  <tbody>
  <tr>
    <th>Date</th>
    <td><?php echo date("d-m-Y", time()); ?></td>
  </tr>
  <tr>
    <th>Time</th>
    <td><?php echo date('H:i:s', time()); ?></td>
  </tr>
  <tr>
    <th>Server</th>
    <td><?php echo gethostname(); ?></td>
  </tr>
  <tr>
    <th>Component</th>
    <td>EngineBlock</td>
  </tr>
  <tr>
      <th>Severity</th>
      <td><?php
          echo isset($this->severity) ?
              htmlentities($this->severity) :
              isset($this->priorityName) ?
                  htmlentities($this->priorityName) :
                  "UNKNOWN"; ?></td>
  </tr>
  <tr>
      <th>SessionID</th>
      <td><?php echo isset($this->sessionid) ? htmlentities($this->sessionid) : htmlentities(session_id()); ?></td>
  </tr>
  <tr>
    <th>Userid</th>
    <td><?php echo isset($this->userId) ? htmlentities($this->userId) : "UNKNOWN"; ?></td>
  </tr>
  <tr>
    <th>IDP</th>
    <td><?php echo isset($this->idp) ? htmlentities($this->idp) : "UNKNOWN"; ?></td>
  </tr>
  <tr>
    <th>SP</th>
    <td><?php echo isset($this->sp) ? htmlentities($this->sp) : "UNKNOWN"; ?></td>
  </tr>
  <tr>
    <th>Message</th>
    <td><pre><?php echo isset($this->message) ? htmlentities($this->message) : "UNKNOWN"; ?></pre></td>
  </tr>
  <tr>
    <th>Location</th>
    <td><?php echo isset($this->location) ? htmlentities($this->location) : htmlentities($_SERVER['SCRIPT_FILENAME']); ?></td>
  </tr>
  <tr>
    <th>Details</th>
    <td><pre><?php echo isset($this->details) ? htmlentities($this->details) : "UNKNOWN"; ?></pre></td>
  </tr>
  <?php foreach ($this->attachments as $key => $attachment): ?>
    <tr>
        <th>Attachment <?php echo is_numeric($key) ? $key+1 : htmlentities($key) ?></th>
        <td><pre><?php echo htmlentities($attachment) ?></pre></td>
    </tr>
  <?php endforeach ?>
  </tbody>
</body>
</html>
