<?php
/**
 * SURFconext EngineBlock
 *
 * LICENSE
 *
 * Copyright 2011 SURFnet bv, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 * @category  SURFconext EngineBlock
 * @package
 * @copyright Copyright © 2010-2011 SURFnet SURFnet bv, The Netherlands (http://www.surfnet.nl)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 */
?>
<html>
<head></head>
<body>
<table>
  <tbody>
  <tr>
    <th>Date</th>
    <td><?= date("d-m-Y", time()); ?></td>
  </tr>
  <tr>
    <th>Time</th>
    <td><?= date('H:i:s', time()); ?></td>
  </tr>
  <tr>
    <th>Server</th>
    <td><?= gethostname(); ?></td>
  </tr>
  <tr>
    <th>Component</th>
    <td>EngineBlock</td>
  </tr>
  <tr>
    <th>Userid</th>
    <td><?= isset($this->userId) ? $this->userId : "UNKNOWN"; ?></td>
  </tr>
  <tr>
    <th>IDP</th>
    <td><?= isset($this->idp) ? $this->idp : "UNKNOWN"; ?></td>
  </tr>
  <tr>
    <th>SP</th>
    <td><?= isset($this->sp) ? $this->sp : "UNKNOWN"; ?></td>
  </tr>
  <tr>
    <th>Message</th>
    <td><?= isset($this->message) ? $this->message : "UNKNOWN"; ?></td>
  </tr>
  <tr>
    <th>Location</th>
    <td><?= $_SERVER['SCRIPT_FILENAME']; ?></td>
  </tr>
  <tr>
    <th>Details</th>
    <td><?= isset($this->details) ? $this->details : "UNKNOWN"; ?></td>
  </tr>
  </tbody>
</body>
</html>