<?php
/** @var Zend_Layout $layout */
$layout = $this->layout();

// Set Layout properties
$layout->title = $layout->title. ' - ' . ucfirst($this->t('logout'));
$layout->header = $layout->title;
$layout->subheader = ucfirst($this->t('logout'));
$layout->footerText = $this->t('footer');
?>
<div class="mod-content">
  <h1>Logout</h1>
  <?= $this->t('logout_description');?>
  <br />
  <?= $this->t('logout_information_link'); ?>
</div>
