<?php
/** @var Zend_Layout $layout */
$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title = $layout->title. ' - ' .$this->t('error_group_oauth');
$layout->header = $layout->title;
$layout->subheader = $this->t('error_group_oauth');
$layout->footerText = $this->t('footer');

?>
<div class="error-wrapper">
    <div class="error-icon"></div>
    <div class="error-text">
        <?= $this->t('error_group_oauth_desc',$providerId); ?>
        <div class="button-row">
            <a href="/profile#MyGroups">
            <?= $this->t('go_back'); ?>
            <span class="btn-wrap-right">&nbsp;</span>
            </a>
        </div>
    </div>
</div>

<?php if ($exception) { ?>
<pre>
    <?php var_dump($exception); ?>
</pre>

<?php if ($exception->xdebug_message) { echo $exception->xdebug_message; } ?>
<?php } ?>
