<?php
  // Determine the selected language, default to english
  $locale = new Zend_Locale();
  $lang = $locale->getLanguage() || 'en';
  $lang = 'en';
  if (isset($_GET['lang'])) {
    $lang = $_GET['lang'];
  } elseif (isset($_POST['lang'])) {
    $lang = $_POST['lang'];
  } elseif (isset($_COOKIE['lang'])) {
    $lang = $_COOKIE['lang'];
  }
  if (!in_array($lang, array('nl','en'))) {
    $lang = 'en';
  }

  $view = new EngineBlock_View();

  $uaSafari = preg_match('~Version/(\d)[\\.\d]+ Safari/~', $_SERVER['HTTP_USER_AGENT'], $matches) ? 'safari' . $matches[1] : '';
?><!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="<?php echo $lang; ?>"> <![endif]-->
<!--[if IE 7]> <html class="no-js ie7 lt-ie10 lt-ie9 lt-ie8" lang="<?php echo $lang; ?>"> <![endif]-->
<!--[if IE 8]> <html class="no-js ie8 lt-ie10 lt-ie9" lang="<?php echo $lang; ?>"> <![endif]-->
<!--[if IE 9]> <html class="no-js ie9 lt-ie10" lang="<?php echo $lang; ?>"> <![endif]-->
<!--[if gt IE 9]> <html class="no-js" lang="<?php echo $lang; ?>"> <![endif]-->
<!--[if !IE]><!--> <html class="no-js <?= $uaSafari ?>" lang="<?php echo $lang; ?>"> <!--<![endif]-->
<head>
  <title><?php echo htmlentities($this->layout()->title, 0, 'UTF-8'); ?></title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="robots" content="noindex, nofollow"/>
  <meta content="ie=edge,chrome=1" http-equiv="x-ua-compatible">
  <meta content="initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width" name="viewport">
  <meta content="yes" name="apple-mobile-web-app-capable">
  <meta content="translucent-black" name="apple-mobile-web-app-status-bar-style">
  <link href="/favicon.ico" rel="shortcut icon">
  <!--[if lte IE 8]><script src="/javascripts/html5shiv.min.js"></script><![endif]-->
  <link href="/stylesheets/application.css" rel="stylesheet" type="text/css" />
  <!-- Firefox CSS -->
  <style>
    @-moz-document url-prefix() {
    <?php // todo remove when Firefox supports line-heights in rem-units ?>
      .comp-links .help {
        line-height:1.7rem !important;
      }
    }
  </style>
</head>
<body class="index">
  <div class="mod-header">
    <h1 class="title">
      <?php echo $this->layout()->subheader; ?>
      <?php if (isset($this->layout()->greenHeader)): ?>
        <strong><?php echo $this->layout()->greenHeader; ?></strong>
      <?php endif; ?>
    </h1>
    <div class="meta">
      <?php function compLanguage($currentLanguage) { ?>
        <?php if (strtoupper($_SERVER['REQUEST_METHOD']) === 'POST'): ?>
          <form method="post" action="">
            <?php foreach ($_POST as $key => $value): ?>
              <input type="hidden" name="<?= EngineBlock_View::htmlSpecialCharsText($key) ?>" value="<?= EngineBlock_View::htmlSpecialCharsText($value) ?>">
            <?php endforeach ?>
            <ul class="comp-language">
              <li>
                <button type="submit" name="lang" value="en"<?php if ($currentLanguage==='en'): ?> class="selected"<?php endif; ?>>EN</button>
              </li>
              <li>
                <button type="submit" name="lang" value="nl"<?php if ($currentLanguage==='nl'): ?> class="selected"<?php endif; ?>>NL</button>
              </li>
            </ul>
          </form>
        <?php else: ?>
          <ul class="comp-language">
            <li>
              <a<?php if ($currentLanguage==='en'): ?> class="selected"<?php endif; ?> href="<?php echo EngineBlock_View::htmlSpecialCharsText(EngineBlock_View::setLanguage('en')); ?>">EN</a>
            </li>
            <li>
              <a<?php if ($currentLanguage==='nl'): ?> class="selected"<?php endif; ?> href="<?php echo EngineBlock_View::htmlSpecialCharsText(EngineBlock_View::setLanguage('nl')); ?>">NL</a>
            </li>
          </ul>
        <?php endif ?>
      <?php } ?>
      <?php if (!isset($this->layout()->displayLanguageSwitcher) || $this->layout()->displayLanguageSwitcher === true): ?>
        <?php compLanguage($lang); ?>
      <?php endif ?>
      <ul class="comp-links">
        <?php if (isset($this->layout()->backLink) && $this->layout()->backLink === true): ?>
        <li>
          <a href="javascript:window.history.back(-2)"><?php echo ucfirst($view->t('return_to_sp')) ?></a>
        </li>
        <?php endif; ?>
        <?php if (isset($this->layout()->helpLink)): ?>
          <li>
            <a href="<?php echo $this->layout()->helpLink; ?>" target="_blank"><?php echo $view->t('help_header'); ?><span class="help">?</span></a>
          </li>
        <?php endif; ?>
      </ul>
    </div>
    <a class="burger" href="#footer"><img src="/images/burger.svg" alt="&#9776;"></a>
  </div>

  <div class="l-container<?php if ($this->layout()->wide === true):?> wide<?php endif; ?>">
      <?php echo $this->layout()->content; ?>
  </div>

  <div id="footer" class="l-footer">
    <nav class="mod-footer">
      <ul class="footer-menu">
        <li class="nav-row left">
          <?php echo $view->t('service_by'); ?> <?php echo $view->t('serviceprovider_link'); ?>
        </li>
        <li class="nav-row">
          <?php if (!isset($this->layout()->displayLanguageSwitcher) || $this->layout()->displayLanguageSwitcher === true): ?>
            <?php compLanguage($lang); ?>
          <?php endif ?>
        </li>
        <li class="nav-row right">
          <ul class="comp-links">
            <?php if (isset($this->layout()->helpLink)): ?>
              <li>
                <a href="<?php echo $this->layout()->helpLink; ?>" target="_blank"><?php echo $view->t('help'); ?></a>
              </li>
            <?php endif; ?>
            <?php if (isset($this->layout()->backLink) && $this->layout()->backLink === true): ?>
              <li>
                <a href="javascript:window.history.back(-2)"><?php echo ucfirst($view->t('return_to_sp')) ?></a>
              </li>
            <?php endif; ?>
            <li>
              <?= $view->t('terms_of_service_link') ?>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>

  <?= $this->layout()->beforeScriptHtml ?>

  <script src="/javascripts/application.js" type="text/javascript"></script>
</body>
</html>
