FROM ghcr.io/openconext/openconext-basecontainers/php72-apache2-node16-composer2:latest
RUN a2enmod ssl
# Copy phpfpm config
COPY docker/ci/app.ini /usr/local/etc/php/conf.d/
RUN rm -rf /etc/apache2/sites-enabled/*
COPY docker/ci/apache2.conf /etc/apache2/sites-enabled/
RUN chown -R www-data: /var/www/
WORKDIR /var/www/html

EXPOSE 443
CMD ["apache2-foreground"]

