FROM ghcr.io/openconext/openconext-basecontainers/php82-apache2-node16-composer2:latest

RUN a2enmod ssl


COPY docker/ci/app.ini /usr/local/etc/php/conf.d/
COPY docker/ci/apache2.conf /etc/apache2/sites-enabled/
RUN chown -R www-data: /var/www/
WORKDIR /var/www/html

EXPOSE 443
CMD ["apache2-foreground"]

