<?php
/** @var Zend_View $this */
define('PARTIAL_DIR', __DIR__ . '/partials/');
require PARTIAL_DIR . 'header-start.php';
?>
        <title><?php echo $this->layout()->title;?></title>

        <link href="/css/ext/jqueryjscrollpane/jquery.jscrollpane.css" rel="stylesheet" type="text/css" />
        <link href="/css/wide/screen.css" rel="stylesheet" type="text/css" />
        <!--[if lt IE 8 ]>
        <link href="/css/wide/screen_ie.css" rel="stylesheet" type="text/css" media="screen" />
        <![endif]-->

        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body class="index">
        <div class="wrapper">
            <div class="header" style="font-weight: bold; font-size: large">
                <?php echo $this->layout()->header; ?>
                <span class="logo">
                    <img src="/media/surfconext.png" alt="SURFconext">
                </span>
            </div>

            <div class="main">
                <!-- Language selection -->
                <ul class="nav">
                    <li class="<?php if ($lang==='en'): ?>active<?php endif; ?>">
                        <a href="<?php echo EngineBlock_View::htmlSpecialCharsText(EngineBlock_View::setLanguage('en')); ?>">EN</a>
                    </li>
                    <li class="<?php if ($lang==='nl'): ?>active<?php endif; ?>">
                        <a href="<?php echo EngineBlock_View::htmlSpecialCharsText(EngineBlock_View::setLanguage('nl')); ?>">NL</a>
                    </li>
                </ul>

                <h1><?php echo $this->layout()->subheader; ?></h1>

                <?php echo $this->layout()->content; ?>

                <div class="bottom">
                    <p>
                        <hr />
                        <?php echo $this->layout()->footerText; ?>
                    </p>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="/javascript/jquery-1.5.1.min.js"></script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
