# see https://github.com/OpenConext/OpenConext-engineblock/blob/cd83052a9da183ae057ba7ba3436195961a75c0c/theme/material/javascripts/application.js#L336
authentication_idp_request_access:
    path:     '/authentication/idp/requestAccess'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:requestAccessAction

# see https://github.com/OpenConext/OpenConext-engineblock/blob/cd83052a9da183ae057ba7ba3436195961a75c0c/theme/material/javascripts/application.js#L231
authentication_idp_perform_request_access_two:
    path:       '/authentication/idp/performRequestAccess'
    methods:    [POST]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:performRequestAccessAction

authentication_idp_process_consent:
    path:       '/authentication/idp/process-consent'
    methods:    [POST]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:processConsentAction

authentication_idp_process_sraminterrupt:
    path:       '/authentication/idp/process-sraminterrupt'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:processSRAMInterrupt

### Sollicited

authentication_idp_sso:
    path:     '/authentication/idp/single-sign-on'
    methods:  [GET,POST]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:singleSignOnAction
        idpHash: ~
        keyId: ~

authentication_idp_sso_keyid:
    path:     '/authentication/idp/single-sign-on/key:{keyId}'
    methods:  [GET,POST]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:singleSignOnAction
        idpHash: ~
    requirements:
        idpHash: .+

authentication_idp_sso_keyid_idphash:
    path:     '/authentication/idp/single-sign-on/key:{keyId}/{idpHash}'
    methods:  [GET,POST]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:singleSignOnAction
    requirements:
       keyId: .+
       idpHash: .+

authentication_idp_sso_idphash:
    path:     '/authentication/idp/single-sign-on/{idpHash}'
    methods:  [GET,POST]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:singleSignOnAction
        keyId: ~
    requirements:
        idpHash: .+

### Unsollicited

authentication_idp_unsolicited_sso:
    path:     '/authentication/idp/unsolicited-single-sign-on'
    methods:  [GET]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:unsolicitedSingleSignOnAction
        idpHash: ~
        keyId: ~

authentication_idp_unsolicited_sso_keyid:
    path:     '/authentication/idp/unsolicited-single-sign-on/key:{keyId}'
    methods:  [GET]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:unsolicitedSingleSignOnAction
        idpHash: ~
    requirements:
        idpHash: .+

authentication_idp_unsolicited_sso_keyid_idphash:
    path:     '/authentication/idp/unsolicited-single-sign-on/key:{keyId}/{idpHash}'
    methods:  [GET]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:unsolicitedSingleSignOnAction
    requirements:
       keyId: .+
       idpHash: .+

authentication_idp_unsolicited_sso_idphash:
    path:     '/authentication/idp/unsolicited-single-sign-on/{idpHash}'
    methods:  [GET]
    defaults:
        _controller: engineblock.controller.authentication.identity_provider:unsolicitedSingleSignOnAction
        keyId: ~
    requirements:
        idpHash: .+
