### Idp

metadata_idp:
    path:       '/authentication/idp/metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:idpMetadataAction
        keyId: ~

metadata_idp_key:
    path:       '/authentication/idp/metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:idpMetadataAction
    requirements:
        keyId: .+

### Sp

metadata_sp:
    path:       '/authentication/sp/metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:spMetadataAction
        keyId: ~

metadata_sp_key:
    path:       '/authentication/sp/metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:spMetadataAction
    requirements:
        keyId: .+

### IdPs
metadata_all_idps:
    path:       '/authentication/proxy/idps-metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:allIdpsMetadataAction
        keyId: ~

metadata_all_idps_key:
    path:       '/authentication/proxy/idps-metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:allIdpsMetadataAction
    requirements:
        keyId: .+

### Edugain
metadata_edugain:
    path:       '/authentication/proxy/edugain-metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:edugainMetadataAction
        keyId: ~

metadata_edugain_key:
    path:       '/authentication/proxy/edugain-metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:edugainMetadataAction
    requirements:
        keyId: .+

### Sfo
metdata_sfo:
    path:       'authentication/sfo/metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.sfo:metadataAction
        keyId: ~

metdata_sfo_key:
    path:       '/authentication/sfo/metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.sfo:metadataAction
    requirements:
        keyId: .+
