### Idp

metadata_idp:
    path:       '/authentication/idp/metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:idpMetadataAction
        keyId: ~

metadata_idp_key:
    path:       '/authentication/idp/metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:idpMetadataAction
    requirements:
        keyId: .+

### Sp

metadata_sp:
    path:       '/authentication/sp/metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:spMetadataAction
        keyId: ''

metadata_sp_key:
    path:       '/authentication/sp/metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:spMetadataAction
    requirements:
        keyId: .+

### IdPs
metadata_all_idps:
    path:       '/authentication/proxy/idps-metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:allIdpsMetadataAction
        keyId: ~

metadata_all_idps_key:
    path:       '/authentication/proxy/idps-metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.metadata:allIdpsMetadataAction
    requirements:
        keyId: .+

### Stepup
metdata_stepup:
    path:       'authentication/stepup/metadata'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.stepup:metadataAction
        keyId: ~

metdata_stepup_key:
    path:       '/authentication/stepup/metadata/key:{keyId}'
    methods:    [GET]
    defaults:
        _controller: engineblock.controller.authentication.stepup:metadataAction
    requirements:
        keyId: .+
