FROM ghcr.io/openconext/openconext-basecontainers/php82-apache2-node16-composer2:latest

RUN a2enmod ssl


COPY docker/php-fpm/app.ini /usr/local/etc/php/conf.d/
COPY docker/php-fpm/apache2.conf /etc/apache2/sites-enabled/
RUN chown -R www-data: /var/www/
WORKDIR /opt/openconext/OpenConext-engineblock

# Copy keys and config
COPY ci/qa-config/files/ /etc/openconext
EXPOSE 443
CMD ["apache2-foreground"]

