<?php
/**
 * @var array $attributes
 */
if (!isset($attributes)) {
    throw new EngineBlock_Exception("Missing required parameter for view /profile/index: attributes");
}

/**
 * @var EngineBlock_Group_Provider_Aggregator $aggregator
 */
if (!isset($aggregator)) {
    throw new EngineBlock_Exception("Missing required parameter for view /profile/index: aggregator");
}

/**
 * @var EngineBlock_AttributeMetadata $metadata
 */
if (!isset($metadata)) {
    throw new EngineBlock_Exception("Missing required parameter for view /profile/index: metadata");
}

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-tabs');

// The tabs
$layout->tabs = array(
    'MyProfile' => $this->t('profile_header_my_profile'),
    'MyGroups' => $this->t('profile_header_my_groups'),
    'MyApps' => $this->t('profile_header_my_apps'),
    'Exit' => $this->t('profile_header_exit'),
);

// The current language
$lang = $this->language();

$layout->header = $this->t('profile_header');
$layout->title = $layout->title . ' - ' . $layout->subheader;
$layout->footerText = $this->t('footer');

$layout->getView()->inlineScript()->appendFile(EngineBlock_View::staticUrl(). '/javascript/screen.js');
$layout->getView()->inlineScript()->appendFile(EngineBlock_View::staticUrl(). '/javascript/profile.js');
$layout->getView()->inlineScript()->appendScript("
    var profile = new Profile();
    profile.init();");
?>
<div id="MyProfile">
    <h2><?php echo $this->t('profile_header_my_profile'); ?></h2>
    <p>
        <?php echo $this->t('profile_store_info'); ?>
    </p>
    <br />

    <table>
        <thead>
            <tr>
                <th><?php echo $this->t('attribute'); ?></th>
                <th><?php echo $this->t('value'); ?></th>
            </tr>
        </thead>
    <?php foreach ($attributes as $attributeId => $attributeValues) { ?>
        <tr>
            <td style="font-weight: bold;">
                <?=$metadata->getName($attributeId, $lang)?>
            </td>
            <td>
                <? /** Single attribute value */ if (count($attributeValues)==1) { ?>
                <?=$attributeValues[0];?>
                <? } /** Multiple attribute values */ else { ?>
                <ul>
                <?php foreach ($attributeValues as $value) { ?>
                    <li><?=$value?></li>
                <?php } ?>
                </ul>
                <? } ?>
            </td>
        </tr>
    <? } ?>
    </table>
</div>
<div id="MyGroups">
    <h2><?php echo $this->t('profile_header_my_groups'); ?></h2>
    <p>
        <?php echo $this->t('profile_group_membership_desc'); ?>
    </p>

    <div id="GroupProviders">
    <?php

    $invalidProviders = $aggregator->getInvalidProviders();
    foreach ($aggregator->getProviders() as $groupProvider):?>
    <h3><a href="#"><?php echo $groupProvider->getDisplayName(); ?></a></h3>
    <div>
        <?php if(count($groupOauth) && array_key_exists($groupProvider->getId(),$groupOauth )): ?>
            <span class="revoke-gp-access"><a href="group-oauth/revoke?provider=<?= urlencode($groupProvider->getId()); ?>"><?= $this->t('profile_revoke_access'); ?></a></span>
        <?php endif; ?>
        <?php
                $groups = array();
        try{
            $groups = $groupProvider->getGroups();
        } catch (EngineBlock_Group_Provider_Exception_Unauthorized $e) {
            $invalidProviders[] = $groupProvider;
        }
        catch(Exception $e) {
            ebLog()->err($e->getMessage());
        }
        if (!empty($groups)):
    ?>
    <ul>
        <?php foreach ($groups as $group): ?>
        <li><?php echo $group->title; ?></li>
        <?php endforeach; ?>
    </ul>

    <?php else: ?>
        <p><?php echo $this->t('profile_no_groups'); ?></p>
    <?php endif; ?>
    </div>
    <?php endforeach; ?>

    <?php
        foreach ($invalidProviders as $groupProvider) {
            /**
             * @var EngineBlock_Group_Provider_Interface $groupProvider
             */

            // Remove the precondition that this provider needs an access token
            $groupProvider->removePreconditionByClassName(
                'EngineBlock_Group_Provider_Precondition_OpenSocial_Oauth_AccessTokenExists'
            );

            // Then if it matches all other preconditions
            // (like 'user should belong to a specific schacHomeOrganization')
            // add it as an OAuth group Provider

            if ($groupProvider->validatePreconditions()) {
                $oauthGroupProviders[] = $groupProvider;
            }
        }
    ?>
    </div>
    <?php if (!empty($oauthGroupProviders)): ?>
    <h3><?php echo $this->t('profile_header_auth_needed'); ?></h3>
    <p><?php echo $this->t('profile_extra_groups_desc'); ?></p>
    <ul>
    <? foreach ($oauthGroupProviders as $oauthGroupProvider): ?>
        <li>
            <a href="/profile/group-oauth/authenticate/<?php echo $oauthGroupProvider->getId();
                ?>?return_url=/">
                <?php echo $oauthGroupProvider->getDisplayName(); ?>
            </a>
        </li>
    <?php endforeach;?>
    </ul>
    <?php endif; ?>
</div>
<div id="MyApps">
    <h2><?php echo $this->t('profile_header_my_apps'); ?></h2>
</div>
<div id="Exit">
    <h2><?php echo $this->t('profile_header_leave_surfconext'); ?></h2>
    <p>
        <?php echo $this->t('profile_leave_surfconext_desc'); ?><br />
        <a href="/profile/delete-user"><?php echo $this->t('profile_leave_surfconext_link'); ?></a>
    </p>
</div>