<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>SURFconext - My Profile</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow"/>
        <link href="/css/screen.css" rel="stylesheet" type="text/css" />
        <!--[if lt IE 8 ]><link href="/css/screen_ie.css" rel="stylesheet" type="text/css" media="screen" /><![endif]-->
    </head>
    <body>
        <div class="wrapper">
            <div class="header"><b><font size="4">SURFconext</font></b><span class="logo"><img src="/media/surfconext.png" alt="SURFconext" /></span></div>
            <div class="main">
                <ul class="nav">
                    <li class="active"><a href="#">EN</a></li>
                </ul>
                <h1>My Profile</h1>
                <div>
                    <p>
                        The following profile data have been provided by your home institution. These data as well as your group membership data (e.g.SURFteams) will be stored in SURFconext and shared with services accessed via SURFconext.
                    </p>
                    <br />

                    <table>
                        <thead>
                            <tr>
                                <th>Attribute</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                    <?php foreach ($attributes as $uid => $attributeValues) { ?>
                        <tr>
                            <td style="font-weight: bold;">
                                <?=$this->getAttributeName($uid, 'en_US')?>
                            </td>
                            <td>
                                <? /** Single attribute value */ if (count($attributeValues)==1) { ?>
                                <?=$attributeValues[0];?>
                                <? } /** Multiple attribute values */ else { ?>
                                <ul>
                                <?php foreach ($attributeValues as $value) { ?>
                                    <li><?=$value?></li>
                                <?php } ?>
                                </ul>
                                <? } ?>
                            </td>
                        </tr>
                    <? } ?>
                    </table>
                    <hr />
                    <h2>Leave SURFconext</h2>
                    <p>
                        If you want to leave SURFconext and delete all the information that is stored about you, please click the link below. Please note that you are also logged out. k <br />
                        <a href="/profile/delete-user">Delete my information!</a>
                    </p>
                </div>
                <div class="bottom">
                    <hr />
                    <p>This service is made possible by <a href='http://www.surfnet.nl/'>SURFnet</a>.</p>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="/javascript/jquery-1.5.1.min.js"></script>
        <script type="text/javascript" src="/javascript/screen.js"></script>
    </body>
</html>