<div class="box">
  <div class="mod-content">
    <h1>Welcome to SURFnet Collaboration Infrastructure EngineBlock - Internal endpoint</h1>
    <p>
        Welcome to the SURFnet COIN Internal endpoint, this endpoint is for SURFnet administrators and services only!<br />
        If you believe you are seeing this in error, please contact <?php echo $this->t('info_mail_link'); ?>.<br />
        <br />
        See also: <a href="/service">/service</a>.<br />
        See also: <a href="/social">/social</a>.<br />
        See also: <a href="/cron">/cron</a>.
    </p>
  </div>
</div>