<?php

/**
 * @var Zend_Layout $layout
 */
use OpenConext\EngineBlockBundle\Pdp\PolicyDecision;

$layout = $this->layout();

$locale = EngineBlock_ApplicationSingleton::getInstance()->getTranslator()->getAdapter()->getLocale();
$logo = null;
if (isset($_SESSION['feedbackInfo']['error_authorization_policy_decision'])) {
    /** @var PolicyDecision $policyDecision */
    $policyDecision = $_SESSION['feedbackInfo']['error_authorization_policy_decision'];

    if ($policyDecision->hasLocalizedDenyMessage()) {
        $policyDecisionMessage = $policyDecision->getLocalizedDenyMessage($locale, 'en');
    } elseif ($policyDecision->hasStatusMessage()) {
        $policyDecisionMessage = $policyDecision->getStatusMessage();
    }
    $logo = $policyDecision->getIdpLogo();
}

// Set Layout properties
$layout->title = $layout->title. ' - ' .$this->t('error_authorization_policy_violation');
$layout->header = $layout->title;
$layout->subheader = $this->t('error_authorization_policy_violation');
$layout->wide = true;

?>
<div class="box">
  <div class="mod-content">
    <h1><?php echo EngineBlock_View::htmlSpecialCharsText($this->layout()->subheader); ?></h1>
    <?= $this->t('error_authorization_policy_violation_info'); ?>
    <?php
        if (isset($policyDecisionMessage)) {
    ?>
        <?php if (!empty($logo->url)) : ?>
            <img src="<?php echo EngineBlock_View::htmlSpecialCharsAttributeValue($logo->url); ?>"
                 class="pull-right"
                 width="<?php echo (int) $logo->width; ?>"
                 height="<?php echo (int) $logo->height; ?>"
            >
        <?php endif; ?>
        <h2><?= EngineBlock_View::htmlSpecialCharsText($policyDecisionMessage)?></h2>

    <?php
    }
    ?>
    <?= $this->t('error_authorization_policy_violation_desc'); ?>

  </div>
</div>
