<?php

/**
 * @var Zend_Layout $layout
 */
use OpenConext\EngineBlock\Metadata\Value\Logo;
use OpenConext\EngineBlockBundle\Pdp\PolicyDecision;

$layout = $this->layout();

$locale = EngineBlock_ApplicationSingleton::getInstance()->getTranslator()->getAdapter()->getLocale();
$logo = false;

if (isset($_SESSION['feedbackInfo']['error_authorization_policy_decision'])) {
    /** @var PolicyDecision $policyDecision */
    $policyDecision = $_SESSION['feedbackInfo']['error_authorization_policy_decision'];

    if ($policyDecision->hasLocalizedDenyMessage()) {
        $policyDecisionMessage = $policyDecision->getLocalizedDenyMessage($locale, 'en');
    } elseif ($policyDecision->hasStatusMessage()) {
        $policyDecisionMessage = $policyDecision->getStatusMessage();
    }

    // Show the IdP logo for status messages
    if ($policyDecision->isIdpSpecificMessage() && $policyDecision->hasIdpLogo()) {
        /** @var Logo $logo */
        $logo = $policyDecision->getIdpLogo();
    }

}

// Set Layout properties
$layout->title = $layout->title. ' - ' .$this->t('error_authorization_policy_violation');
$layout->header = $layout->title;
$layout->subheader = $this->t('error_authorization_policy_violation');
$layout->wide = true;

?>
<div class="box">
  <div class="mod-content">
    <h1><?php echo htmlentities($this->layout()->subheader, 0, "UTF-8"); ?></h1>
    <?= $this->t('error_authorization_policy_violation_info'); ?>
    <?php
        if (isset($policyDecisionMessage)) {
    ?>
        <?php if ($logo !== false) : ?>
            <img src="<?php echo $logo->getUrl(); ?>"
                 class="pull-right"
                 width="<?php echo $logo->getWidth(); ?>"
                 height="<?php echo $logo->getHeight(); ?>"
            >
        <?php endif; ?>
        <h2><?= EngineBlock_View::htmlSpecialCharsText($policyDecisionMessage)?></h2>

    <?php
    }
    ?>
    <?= $this->t('error_authorization_policy_violation_desc'); ?>

  </div>
</div>
