<?php

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();

// Set Layout properties
$layout->title = $layout->title. ' - ' .$this->t('error_authorization_policy_violation');
$layout->header = $layout->title;
$layout->subheader = $this->t('error_authorization_policy_violation');
$layout->wide = true;

?>
<div class="box">
  <div class="mod-content">
    <h1><?php echo htmlentities($this->layout()->subheader, 0, "UTF-8"); ?></h1>
    <?= $this->t('error_authorization_policy_violation_info'); ?>
    <?php
      if (!empty($_SESSION['feedbackInfo']) && is_array($_SESSION['feedbackInfo'])) {
    ?>
      <h2><?= EngineBlock_View::htmlSpecialCharsText($_SESSION['feedbackInfo']['error_authorization_policy_violation_name'])?></h2>
    <?php
    }
    ?>
    <?= $this->t('error_authorization_policy_violation_desc'); ?>

  </div>
</div>
