<?php

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
//$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title = $layout->title. ' - ' .$this->t('error_no_consent');
$layout->header = $layout->title;
$layout->subheader = $this->t('error_no_consent');
$layout->footerText = $this->t('footer');

?>
<div class="mod-content">
  <h1><?php echo htmlentities($this->layout()->subheader, 0, "UTF-8"); ?></h1>
  <div class="error-wrapper">
      <div class="stop-text">
          <?= $this->t('error_no_consent_desc');

          require_once realpath(__DIR__ . '/../../../Default/View/Error/include/footer.php'); ?>
</div>