<?php

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();

// The current language
$lang = $this->language();

$layout->header = $this->t('vomanage_header');
$layout->subheader = $this->t('vomanage_sub_header');
$layout->title = $layout->title . ' - ' . $layout->subheader;
$layout->footerText = $this->t('footer');

?>
<div>
    <br/>
        <h2><?php echo $this->t('vomanage_delete_intro'); ?></h2>
    <br/>
    Virtual Organisation: <strong><?php echo $vo_id; ?></strong>
    <br/>
    <br/>
    
<?php if ($data['formaction'] == 'delete') : ?>
<div>
    <?php if ($errors['sql'] != 0) : ?>
        <p>
            <?php echo $this->t('vomanage_delete_fail'); ?>:
            <font color="red"><strong><?php echo $this->t($errors['sql']); ?></strong></font>
        </p>
    <?php endif; ?>
    <?php if (count($errors) === 0) : ?>
        <p>
            <?php echo $this->t('vomanage_delete_success'); ?>
        </p>
    <?php endif; ?>
    <br />
    <form id="actionform" method="POST">
        <input type="hidden" id="vo_id" name="vo_id" value="<?php echo htmlentities($vo_id); ?>"/>
        <input type="hidden" id="action" name="action" value="Index"/>
        <input type="submit" name="backtoindex" value="<?php echo $this->t('vomanage_delete_back'); ?>"/>
    </form>
</div>
<?php endif; ?>

<?php if ($data['formaction'] != 'delete') : ?>    
    <p>
        <?php echo $this->t('vomanage_delete_question'); ?>
    </p>
    <table class="formtable" style="margin-left: 10px">
        <tr>
            <td style="font-weight: bold;">
                <label for="sp_entity_id">SP entity id</label>
            </td>
            <td>
                <?php echo htmlentities($data['sp_entity_id_display']); ?>
            </td>
        </tr>
        <tr>
            <td style="font-weight: bold;">
                <label for="user_id_pattern">User id pattern</label>
            </td>
            <td>
                <?php echo htmlentities($data['user_id_pattern']); ?>
            </td>
        </tr>
        <tr>
            <td style="font-weight: bold;">
                <label for="attribute_name_saml">Attribute name (SAML)</label>
            </td>
            <td>
                <?php echo htmlentities($data['attribute_name_saml']); ?>
            </td>
        </tr>
        <tr>
            <td style="font-weight: bold;">
                <label for="attribute_name_opensocial">Attribute name (OpenSocial)</label>
            </td>
            <td>
                <?php echo htmlentities($data['attribute_name_opensocial']); ?>
            </td>
        </tr>
        <tr>
            <td style="font-weight: bold;">
                <label for="attribute_value">Attribute value</label>
            </td>
            <td>
                <?php if (count($data['attribute_value']) > 1) : ?>
                <ul>
                    <?php foreach ($data['attribute_value'] as $value) : ?>
                    <li><?php echo htmlentities($value); ?></li>
                    <?php endforeach; ?>
                </ul>
                <?php elseif (count($data['attribute_value']) == 1) : ?>
                    <?php echo array_pop($data['attribute_value']); ?>
                <?php else : ?>
                    <?php echo htmlentities($data['attribute_value']); ?>
                <?php endif; ?>
                
            </td>
        </tr>
    </table>
    <br/>
    <form id="actionform" method="POST">
        <input type="hidden" id="id" name="id" value="<?php echo $id ?>"/>
        <input type="hidden" id="vo_id" name="vo_id" value="<?php echo $vo_id; ?>"/>
        <input type="hidden" id="action" name="action" value="Delete"/>
        <input type="hidden" id="formaction" name="formaction" value=""/>
        <input type="button" name="delete" value="<?php echo $this->t('vomanage_yes'); ?>" 
               onclick="$('#formaction').val('delete'); $('#actionform').submit();"/>
        <input type="button" name="cancel" value="<?php echo $this->t('vomanage_no'); ?>" 
               onclick="$('#formaction').val('cancel'); $('#actionform').submit();"/>
    </form>
<?php endif; ?>
    
</div>