<?php

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();

// The current language
$lang = $this->language();

$layout->header = $this->t('vomanage_header');
$layout->subheader = $this->t('vomanage_sub_header');
$layout->title = $layout->title . ' - ' . $layout->subheader;
$layout->footerText = $this->t('footer');

?>
<div>
    <br/>
        <h2><?php echo $this->t('vomanage_selectvo_intro'); ?></h2>
    <br />

    <p><?php echo $this->t('vomanage_selectvo_header'); ?></p>
    <form method="POST">
    <select id="vo_id" name="vo_id">
    <?php foreach ($resultSet as $i => $row) : ?>
        <option value="<?php echo $row['vo_id']; ?>">
            <?php echo $row['vo_id']; ?> (<?php echo $row['vo_type']; ?>)
        </option>
    <?php endforeach; ?>
    </select>
    &nbsp;
    <input type="submit" value="<?php echo $this->t('vomanage_selectvo_submit'); ?>"/>
    </form>
</div>
