<?php

/**
 * @var EngineBlock_View $this
 */

$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title = $layout->title. ' - ' .$this->t('error_generic');
$layout->header = $layout->title;
$layout->subheader = $this->t('error_generic');
$layout->footerText = $this->t('footer');

?>
<div class="error-wrapper">
    <div class="error-icon"></div>
    <div class="error-text">
        <?= $this->t('error_generic_desc'); ?>

<?php require_once __DIR__ . '/include/footer.php';
