<?php

/**
 * @var Zend_Layout $layout
 */
$layout = $this->layout();
$layout->setLayout('1-column-blue-grey-narrow');

// Set Layout properties
$layout->title = $layout->title. ' - ' .$this->t('error_404');
$layout->header = $layout->title;
$layout->subheader = $this->t('error_404');
$layout->footerText = $this->t('footer');

?>
<div class="error-wrapper">
    <div class="error-icon"></div>
    <div class="error-text">
        <?= $this->t('error_404_desc'); ?>
        <br /><br />
        <div class="button-row">
            <a href="#" id="GoBack"  class="submit button-tertiary" onclick="history.back(-2); return false;">
                <?= $this->t('go_back'); ?>
                <span class="btn-wrap-right">&nbsp;</span>
            </a>
        </div>
    </div>
</div>