<?php

declare(strict_types=1);

namespace OpenConext\EngineBlock\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260814091601 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE consent (
                consent_date      TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                hashed_user_id    VARCHAR(80)                     NOT NULL,
                service_id        VARCHAR(255)                    NOT NULL,
                attribute         VARCHAR(80)                     NOT NULL,
                attribute_stable  VARCHAR(80)                     DEFAULT NULL,
                consent_type      VARCHAR(20)                     DEFAULT 'explicit' NOT NULL,
                deleted_at        TIMESTAMP(0) WITHOUT TIME ZONE,
                PRIMARY KEY (hashed_user_id, service_id, deleted_at)
            )
            SQL);
        $this->addSql('CREATE INDEX consent_hashed_user_id_idx ON consent (hashed_user_id)');
        $this->addSql('CREATE INDEX consent_service_id_idx ON consent (service_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE saml_persistent_id (
                persistent_id           CHAR(40) NOT NULL,
                user_uuid                CHAR(36) NOT NULL,
                service_provider_uuid    CHAR(36) NOT NULL,
                PRIMARY KEY (persistent_id)
            )
            SQL);
        $this->addSql('CREATE INDEX user_uuid ON saml_persistent_id (user_uuid, service_provider_uuid)');
        $this->addSql("COMMENT ON COLUMN saml_persistent_id.persistent_id IS 'SHA1 of COIN: + user_uuid + service_provider_uuid'");

        $this->addSql(<<<'SQL'
            CREATE TABLE service_provider_uuid (
                uuid                          CHAR(36)     NOT NULL,
                service_provider_entity_id    VARCHAR(1024) NOT NULL,
                PRIMARY KEY (uuid)
            )
            SQL);
        $this->addSql('CREATE INDEX service_provider_entity_id ON service_provider_uuid (service_provider_entity_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE sso_provider_roles_eb6 (
                id                             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                entity_id                      VARCHAR(255)  NOT NULL,
                name_nl                        VARCHAR(255),
                name_en                        VARCHAR(255),
                name_pt                        VARCHAR(255) ,
                description_nl                 VARCHAR(255),
                description_en                 VARCHAR(255),
                description_pt                 VARCHAR(255),
                display_name_nl                VARCHAR(255),
                display_name_en                VARCHAR(255),
                display_name_pt                VARCHAR(255),
                logo                           JSON        ,
                organization_nl_name           JSON          DEFAULT NULL,
                organization_en_name           JSON          DEFAULT NULL,
                organization_pt_name           JSON          DEFAULT NULL,
                keywords_nl                    VARCHAR(255),
                keywords_en                    VARCHAR(255),
                keywords_pt                    VARCHAR(255),
                certificates                   JSON        ,
                workflow_state                 VARCHAR(255)  NOT NULL,
                contact_persons                JSON        ,
                name_id_format                 VARCHAR(255)  DEFAULT NULL,
                name_id_formats                JSON          NOT NULL,
                single_logout_service          JSON          DEFAULT NULL,
                requests_must_be_signed         BOOLEAN       NOT NULL,
                manipulation                   TEXT        ,
                coins                          JSON          NOT NULL,
                mdui                           JSON          NOT NULL,
                type                           VARCHAR(255)  NOT NULL,
                attribute_release_policy       JSON          DEFAULT NULL,
                assertion_consumer_services    JSON          DEFAULT NULL,
                allowed_idp_entity_ids         JSON          DEFAULT NULL,
                allow_all                      BOOLEAN       DEFAULT NULL,
                requested_attributes           JSON          DEFAULT NULL,
                support_url_en                 VARCHAR(255)  DEFAULT NULL,
                support_url_nl                 VARCHAR(255)  DEFAULT NULL,
                support_url_pt                 VARCHAR(255)  DEFAULT NULL,
                enabled_in_wayf                BOOLEAN       DEFAULT NULL,
                single_sign_on_services        JSON          DEFAULT NULL,
                consent_settings               TEXT          DEFAULT NULL,
                shib_md_scopes                 JSON          DEFAULT NULL,
                idp_discoveries                JSON          DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_sso_provider_roles_type ON sso_provider_roles_eb6 (type)');
        $this->addSql('CREATE INDEX idx_sso_provider_roles_entity_id ON sso_provider_roles_eb6 (entity_id)');
        $this->addSql('CREATE UNIQUE INDEX idx_sso_provider_roles_entity_id_type ON sso_provider_roles_eb6 (type, entity_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
                collab_person_id    VARCHAR(255) NOT NULL,
                uuid                 CHAR(36)     NOT NULL,
                PRIMARY KEY (collab_person_id)
            )
            SQL);
        $this->addSql("COMMENT ON COLUMN \"user\".collab_person_id IS '(DC2Type:engineblock_collab_person_id)'");
        $this->addSql("COMMENT ON COLUMN \"user\".uuid IS '(DC2Type:engineblock_collab_person_uuid)'");
        $this->addSql('CREATE UNIQUE INDEX uq_user_uuid ON "user" (uuid)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE consent');
        $this->addSql('DROP TABLE saml_persistent_id');
        $this->addSql('DROP TABLE service_provider_uuid');
        $this->addSql('DROP TABLE sso_provider_roles_eb6');
        $this->addSql('DROP TABLE "user"');
    }
}
