name: run cypress
on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:
    # run at 6 hour UTC
    schedule:
        -   cron: "0 6 * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        strategy:
            matrix:
                php: [ php72 ]
        env:
            PROD_PHP: php72
            DOCKER_COMPOSE: docker compose -f docker-compose.yml -f docker-compose-${{matrix.php}}.yml
        steps:
            -   name: Checkout
                uses: actions/checkout@master

            -   name: Build Docker environmnent
                run: |
                    cd docker && ./docker-setup.sh

            -   name: Build Docker environmnent
                run: |
                    cd docker && ./docker-runcypress.sh
